### ISSUE TITLE
Q: Should Giraffe.SOAP go into this repo? 

### ISSUE THREAD

**Issue by forki** [giraffe-fsharp/Giraffe#153]
Since asp.net core does not support WCF I have started to build a SOAP combinator lib for Giraffe. Do you think it should go here as own nuget package or into separate repo.

**Comment by dustinmoris** [comment]
Hey, that sounds awesome. As you know I am currently setting up the org, so it could be nice to have it there at least as a separate repo where you can take ownership if you want but I'd be also happy if you want to keep it somewhere else. Regardless of where the code will be I think it should be a separate NuGet package.

**Comment by gerardtoconnor** [comment]
Would be nice if this could be held in src like Giraffe.Razor & Giraffe.DotLiquid as I see potential usage at least on par with DotLiquid? Many enterprise api people will love this being easily added.

**Comment by dustinmoris** [comment]
@forki: I can create Giraffe.SOAP under giraffe-fsharp now and make you the owner of this repo so you can push and maintain this NuGet package going forward if you like?

**Comment by forki** [comment]
yes please. thank you

**Comment by dustinmoris** [comment]
Ok you should be able to move your code now ;)
