### ISSUE TITLE
Extend build script to take care of NuGet push instead of using AppVeyor built in NuGet client

### ISSUE THREAD

**Issue by dustinmoris** [giraffe-fsharp/Giraffe#157]
NuGet packages were successfully pushed, but still requires to be fixed, see: https://ci.appveyor.com/project/dustinmoris/giraffe/build/0.1.0-beta-310-359

`NuGet account requires protocol version 4.1.0 - using NuGet command line tool`

**Comment by forki** [comment]
use paket. /shrug

**Comment by dustinmoris** [comment]
@forki Yeah, well I actually just use the one that comes out of the box with AppVeyor so I didn't have to maintain either myself: https://github.com/dustinmoris/Giraffe/blob/master/appveyor.yml#L20

Actually would be nice if AppVeyor would allow another provider like Paket to restore and push packages. Is this something you think Paket would be interested to raise with AppVeyor?

**Comment by forki** [comment]
@dustinmoris you are going the road stright into vendor lockin.

From my OSS experience this exactly what you want to avoid. Ask community to write proper build / deploy script if you don't want to do it yourself. Commit everything that is needed.

**Comment by JonCanning** [comment]
Is this using `dotnet nuget push`?

**Comment by dustinmoris** [comment]
@forki 
> going the road stright into vendor lockin
this is true, it's normally what I avoid in other projects as well, but here I must have set it up very basic in the beginning. I actually even blogged about this myself a while ago ^^

I'll create an issue to move to a script based push...

@JonCanning not sure what AppVeyor uses under the hood, I think they do a push via their own HTTP web request if I remember correctly, so I think they might have to update their http headers to include the protocol version now.

**Comment by forki** [comment]
@dustinmoris yes I'm not arguing that they make it easy to start. Same with TeamCity and other CI systems. The problem is that things will become hard eventually.
