### ISSUE TITLE
TokenRouter needs explicit GET when POST is used

### ISSUE THREAD

**Issue by forki** [giraffe-fsharp/Giraffe#158]
Reminder for @gerardtoconnor ;-)

sent you actual routes in screenshot. It's along the lines of:

     router notfound [
          subRoute "/api" [
               // get routes
               route "/hey" f
               POST [
                  route "/there" f2
               ]
     ]

not working. but following is:

     router notfound [
          subRoute "/api" [
               GET [
                   route "/hey" f
               ]
               POST [
                  route "/there" f2
               ]
     ]

**Comment by gerardtoconnor** [comment]
I'll look into this, thanks for raising.

The issue relates to it being able to partially match the non-filtered root before realizing it's a dead-end but there may have been a route possible in filtered routes earlier in the tree.

There are a few ways to fix but I want to make sure it's performant & clean so please bear with me and use the explicit route filtering as you have for now thanks.

**Comment by gerardtoconnor** [comment]
@forki I know breaking changes are annoying but when I created the method filter functions I overlooked the fact that many people like to do filter as last leg in chain eg:
```f#
router notfound [
      subRoute "/api" [
           subRoute "/hey" [
                GET f1
                POST f2
           ]
           POSTGRP [
              route "/there" f3
           ]
 ]
```
So I am wondering how I handle it and if I have two separate functions for each method eg for `GET`:

1. `GET`       : HttpHandler -> Node -> Node
2. `GETGRP` : (Node -> Node) list -> Node

not changing anything yet but along with this bug fix want to make sure fixes against this issue as 
```f#
router notfound [
      subRoute "/api" [
           GET [ 
                route "/hey" f1 
           ]
           POST [ 
                route "/hey" f2
           ]
           POST [
              route "/there" f3
           ]
 ]
```
Is bit repetitive and frustrating for user having to write `route "/hey"` twice?

**Comment by dustinmoris** [comment]
Moved to https://github.com/giraffe-fsharp/Giraffe.TokenRouter/issues/1
