### ISSUE TITLE
Giraffe back-end for SAFE stack?

### ISSUE THREAD

**Issue by boyedarat** [giraffe-fsharp/Giraffe#161]
Would like to follow upon any progress with getting a sample implementation of Giraffe+SAFE stack?
There was a comment from @dustinmoris on this issue for a working sample:
https://github.com/SAFE-Stack/SAFE-BookStore/issues/196

Getting SAFE to work with Giraffe seems tough. Maybe because I am still a newb to all of this.

**Comment by forki** [comment]
Giraffe works nicely with safe. Have it working. But no time at the moment
to up the bookstore

Am 02.12.2017 16:07 schrieb "boyedarat" <notifications@github.com>:

**Comment by dustinmoris** [comment]
@boyedarat Haven't had time to make any progress yet, sorry. It's still on the todo list though. Any help on this would be more than welcome as well. Meanwhile maybe @forki can assist you with answering any specific questions you might have?

**Comment by forki** [comment]
Sure

Am 03.12.2017 22:27 schrieb "Dustin Moris Gorski" <notifications@github.com

**Comment by boyedarat** [comment]
@forki Could you share the parts where you replaced Suave with Giraffe? Not familiar with which parts of Suave matches with Giraffe. I am not familiar with Paket either.

**Comment by forki** [comment]
Suave and giraffe are the Webservers they replace each other completely

Am 07.12.2017 21:50 schrieb "boyedarat" <notifications@github.com>:

**Comment by boyedarat** [comment]
@forki what is the equivalent for "startWebServer config webPart"?

**Comment by lambdakris** [comment]
The "equivalent" of the Suave "startWebServer" function in Giraffe would be an instance of the [ASP.NET Core WebHostBuilder class](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/hosting?tabs=aspnetcore2x) with the use of the Configure extension method or a [custom Startup class](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/startup). Something like
```
WebHostBuilder().Configure(fun builder -> builder.UseGiraffe(...your handlers...)).UseKestrel().Build().Run()
```
This usage of the ASP.NET Core [hosting](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/hosting?tabs=aspnetcore2x) and [startup](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/startup) functionality with Giraffe is somewhat covered in the ["Doing it manually" part of the Giraffe readme](https://github.com/giraffe-fsharp/Giraffe#doing-it-manually) and can also be seen at work in the [SampleApp Program.fs file](https://github.com/giraffe-fsharp/Giraffe/blob/develop/samples/SampleApp/SampleApp/Program.fs#L149).

As I'm sure you can already tell, there is some additional thought that has to be put into how to integrate/replace the ASP.NET Core host builder code with the SAFE-Bookstore Server entry code (what is in the Program.fs and WebServer.fs files). But hopefully this information can help you along.

**Comment by boyedarat** [comment]
Translated the server code the best I could, compiles fine, but I can't get the web server started. Here is the error that I got:
`[HPM] Error occurred while trying to proxy request /api/init from localhost:8080 to http://localhost:8085 (ECONNREFUSED) (https://nodejs.org/api/errors.html#errors_common_system_errors)`

Here is the converted code for the server module:
```
open System
open System.IO

open Microsoft.AspNetCore.Builder
open Microsoft.AspNetCore.Cors.Infrastructure
open Microsoft.AspNetCore.Hosting
open Microsoft.AspNetCore.Http

open Microsoft.Extensions.Logging
open Microsoft.Extensions.DependencyInjection

open Giraffe

open Shared


let webRoot = Path.Combine("..","Client") |> Path.GetFullPath

let getInitCounter () : Async<Counter> = async { return 42 }

let webApp =
  choose [
    route "/api/init" >=> fun (next : HttpFunc) (ctx : HttpContext) ->
      task {
        let! counter = getInitCounter()
        return! Successful.OK (string counter) next ctx
      }
    route "/" >=> htmlFile webRoot
    setStatusCode 404 >=> text "Not Found"]

let configureCors (builder : CorsPolicyBuilder) =
  builder.WithOrigins("http://localhost:8085").AllowAnyMethod().AllowAnyHeader() |> ignore


let errorHandler (ex : Exception) (logger : ILogger) =
    logger.LogError(EventId(), ex, "An unhandled exception has occurred while executing the request.")
    clearResponse >=> setStatusCode 500 >=> text ex.Message

let configureApp (app : IApplicationBuilder) =
  app.UseCors(configureCors)
    .UseGiraffeErrorHandler(errorHandler)
    .UseStaticFiles()
    .UseGiraffe(webApp)

let configureLogging (builder : ILoggingBuilder) =
  let filter (l : LogLevel) = l.Equals LogLevel.Error
  builder.AddFilter(filter).AddConsole().AddDebug() |> ignore

let configureServices (services : IServiceCollection) =
    services.AddCors() |> ignore

[<EntryPoint>]
let main _ =
  WebHostBuilder()
    .UseKestrel()
    .UseIISIntegration()
    .UseWebRoot(webRoot)
    .Configure(Action<IApplicationBuilder> configureApp)
    .ConfigureServices(configureServices)
    .ConfigureLogging(configureLogging)
    .Build()
    .Run()
  0
```
Source: https://github.com/SAFE-Stack/SAFE-template/blob/master/Content/src/Server/Program.fs

**Comment by dustinmoris** [comment]
I am going to close this as there is already an issue open for this in the SAFE-Stack repo and @forki has produced the first working version of "GAFE" in this pull request: https://github.com/SAFE-Stack/SAFE-BookStore/pull/255
