### ISSUE TITLE
Add CONTRIBUTING.md

### ISSUE THREAD

**Issue by dustinmoris** [giraffe-fsharp/Giraffe#164]
With increasing maintainers + helpers this is needed.

**Comment by JonCanning** [comment]
What do you think of C4?

https://rfc.zeromq.org/spec:42/C4/

**Comment by dustinmoris** [comment]
wow thanks, that looks very comprehensive! I like a lot of what's written in it. I think I will probably take some parts of it and try to compile something smaller for a start so that it doesn't feel like a long T&C which nobody has the time to read ^^

**Comment by JonCanning** [comment]
I heard Peter Hintjens talking about C4 once, and the principle as I understood it was that people contributed, and that contribution was encouraged by accepting and merging PRs quickly. If you don't like something, submit your own PR, no bikeshedding, just keep the development flowing.

**Comment by TheAngryByrd** [comment]
Also a coworker turned me on to https://mozillascience.github.io/working-open-workshop/contributing/

**Comment by dustinmoris** [comment]
Thanks that is a really nice and helpful tutorial! I'll try to find some time soon to go through all of this and put a first draft together!

**Comment by dustinmoris** [comment]
Hi, I haven't had time to do this issue yet and it's kind of not on my priority list since there's a little contributing section in the README and so far it has worked well enough so I'm inclined to close this issue as I don't see myself doing this any time soon,  but if someone was to provide a PR I'll happily accept it!
