### ISSUE TITLE
HttpStatusCodeHandlers are not found under Giraffe namespace like the rest of the handlers

### ISSUE THREAD

**Issue by lambdakris** [giraffe-fsharp/Giraffe#166]
## Summary

I am not sure if this is by design, but the recently added HTTP Status Code handlers are not currently found under the Giraffe namespace like the other handlers are.

## Reproduction
Create Giraffe project using template
```
dotnet new giraffe
```
Open Program.fs in editor
```
...
let webApp =
    choose [
        GET >=>
            choose [
                route "/" >=> razorHtmlView "Index" { Text = "Hello world, from Giraffe!" }
            ]
        setStatusCode 404 >=> text "Not Found" ]
...
```
On line 26, try to replace 'setStatusCode 404 >=> text "Not Found"' with NOT_FOUND ""
```
...
let webApp =
    choose [
        GET >=>
            choose [
                route "/" >=> razorHtmlView "Index" { Text = "Hello world, from Giraffe!" }
            ]
        NOT_FOUND "" ]
...
```
## Expected
HTTP Status Code handlers should be in scope when you open Giraffe, like the rest of the handlers

## Actual
HTTP Status Code handlers are not in scope when you open Giraffe, unlike the rest of the handlers

## Workaround
open Giraffe.HttpStatusCodeHandlers.RequestErrors

...or more generally, open the module under HttpStatusCodeHandlers that contains the status code handler you need

## Environment
- Windows 10
- .NET Core 2.0
- Giraffe 0.1.0-beta-400

**Comment by lambdakris** [comment]
Nevermind, just realized that the status code submodules _are_ exposed under the Giraffe namespace and it is documented to qualify the handlers with the submodule that they belong to, ie. `RequestErrors.NOT_FOUND`

**Comment by gerardtoconnor** [comment]
Opening the RequestErrors module will work in case prefixing is verbose
