### ISSUE TITLE
Question about nesting routes under/within handlers...if that makes sense

### ISSUE THREAD

**Issue by lambdakris** [giraffe-fsharp/Giraffe#167]
Ok, I suspect that the reply will probably be something along the lines of "Why would you want to do that" or "You are heading down the wrong path", but here goes...

Is something like this possible? Or what would be an alternative?
```

let webApp =
    TokenRouter.router (RequestErrors.NOT_FOUND "") [
        route "/" (text "home")
        subRoute "/sub" [
            fun x ->
                let context = ??? // somehow intercept the context
                let query = context.BindQuery<Model>() // get the query 
                let data = db.FetchData<Data>(query.dataId) // get some data that all sub handlers will use
                GET [
                    route "/" (subHandler1 data)
                    route "/a" (subHandler2 data)
                    route "/b" (subHandler3 data)
                ] x
        ]
    ]
```

In my mind, it seems like it might be useful to enrich requests with data or logic as they go down a particular routing path. This seems like it could be a lightweight way to implement authorization and stuff like that. Basically it seems like it would provide a way to execute logic or mount data that is common to all things under a particular path segment...

**Comment by dustinmoris** [comment]
I haven't tried your code yet, but I don't see anything which wouldn't work. Is your question regarding whether you can access the `HttpContext` from within the sub route? If yes, then the answer is yes, the `x` parameter should represent `HttpContext` if I am not mistaken, but I'd have to paste your code to try it out.

**Comment by gerardtoconnor** [comment]
Hi Guys, this wont work for a number of reasons in current form

- need to open TokenRouter module, not prepend it to only router as all routing functions are in this namespace too
- as @dustinmoris points out, you need to have a 2 arg  `fun next ctx ->` to be a handler but in this case will still not work as subroute expects child routes not a handler

I would recommend not mixing data mapping in routing pipeline and you may be better off creating a simple helper function to call in your handlers. It may seem like a nice short cut now but will lead to bigs and maintenance issues  as you app grows

```fsharp
open TokenRouter
let getData ctx ->
      let query = ctx.BindQuery<Model>() // get the query 
      db.FetchData<Data>(query.dataId)

let subhandler1 :HttpHandler = fun next ctx -> let data =  getData ctx ; ...

let notFound = (RequestErrors.NOT_FOUND "")
let webApp =
    router  notFound  [
        route "/" (text "home")
        route "/sub" [
                GET [
                    route "/" (subHandler1 data)
                    route "/a" (subHandler2 data)
                    route "/b" (subHandler3 data)
                   ]
                ] 
    ]
```

**Comment by gerardtoconnor** [comment]
Additionally, enriched additional data does not fit into the composed pipeline so cannot be optimized at initialization and instead becomes a wasteful last minute runtime decision every time. It becomes an abuse of scope closures where it is just not needed.

**Comment by lambdakris** [comment]
Yeah, figured this was antithetical to the token router. Sorry for the errors in the code, it was more pseudo code since I new it would not compile regardless of what namespace I opened or arguments I declared. 

I get what you mean about long term maintenance, but I can't help but think that it could help to lift and consolidate common code out of sibling handlers to a parent handler, eliminating the risk of another developer forgetting to add that common code in a new sibling handler. 

Another thing that I came across that I have some doubts about is whether the method filters for the token router only work on a list of Node -> Node functions? That is what it seemed like to me which means that you have to group by method rather than URI. I imagine this is done for performance, but it does feel a bit weird to bubble that concern up to the dev who probably might be expecting to keep methods for a resource grouped together.

**Comment by gerardtoconnor** [comment]
@lambdakris 
in the token router, all routing functions return a function of `node->node` as it is how it threads the routing data through the radix tree parent node to create a compiled tree for runtime. 

`route`, `routef`, `GET` (etc) & `subRoute` are all mapping functions that have a signature `Node -> Node` fed into the base router that compiles everything. I would prefer if the details and this transform were not visible but the old other way to replicate this would be through DUs and that is not as clean or straight forward.

you mention that you have to group by method rather then URI, you can format which ever way you like, both `GET` can `subRoute` take a list to allow you to group by both, the final `route` / `routef` are endpoint completions of matches and makes sense these do not group.

If you have any ideas on how we can improve this we are more then happy to work on. if you want to inject data into context during routes, the context `Items` dictionary is also there to hold values.

**Comment by lambdakris** [comment]
@gerardtoconnor I look forward to learning more about the token router, it is pretty impressive.

Regarding the method filters, I guess I am just used to doing something like this with the combinator style router...
```
let appTree : HttpHandler =
    choose [
        route "/resource1" >=> choose [
            GET >=> (text "get resource1")
            POST >=> (text "post resource1")
        ]
        route "/resource2" >=> choose [
            ...
        ]
        ...
    ]
```
With the token router what I was able to come up with was...
```
let appTree : HttpHandler =
    router (RequestErrors.NOT_FOUND "") [ 
        subRoute "/resource1" [
            GET [
                route "/" (text "get resource1")
            ]
            POST [
                route "/" (text "post resource1")
            ]
        ]
        subRoute "/resource2" [
           ...
        ]
        ...
    ]
```
I see why different things are possible with the two routers, but based on the example above, I would hesitate to organize my apis by resource with the token router. It feels more natural to do something like this...
```
let appTree : HttpHandler =
    router (RequestErrors.NOT_FOUND "") [ 
            GET [
                route "/resource1" (text "get resource1")
                route "/resource2" (text "get resource2")
                ...
            ]
            POST [
                route "/resource1" (text "post resource1")
                route "/resource2" (test "post resoruce2")
                ...
            ]
        ]
    ]
```
But truthfully, I think I need to spend more time with the library and the techniques used before I can make any concrete suggestions. Regardless, I think what you guys have done so far is great and am eager to try it on some real world projects.

I'll go ahead and close since the questions I posed here have essentially been answered, though I'll be glad if anyone has anything else to add...
