### ISSUE TITLE
dotnet new giraffe not working with dotnet 2.1.2

### ISSUE THREAD

**Issue by dsincl12** [giraffe-fsharp/Giraffe#168]
I haven't investigated further yet but it works fine with 2.0.3 but nothing happens on 2.1.2 when the command is run.

**Comment by dustinmoris** [comment]
Where did you test it with `2.1.2`? The [latest .NET Core SDK is 2.0.3](https://www.microsoft.com/net/download/macos) for me. Also when I look at [the roadmap](https://github.com/dotnet/core/blob/master/roadmap.md) I see that the first preview will be next year and a stable to be expected much later in the year Q2 2018.

**Comment by dsincl12** [comment]
I had it on my home workstation but I seriously have no clue how I got that version. To get back to 2.0.3 I had to delete the 2.1.2 folder. Haven't installed any RC or Beta on this computer. Anyway I'll just close this one.

**Comment by dustinmoris** [comment]
That's weird.. did you install the latest VS update or something else which might have accidentally given you some insider build perhaps? :)

**Comment by dsincl12** [comment]
Yeah maybe, I didn't get a update notification for VS 15.5 so I downloaded and upgraded it myself.
