### ISSUE TITLE
Unable to create a new project with `dotnet new giraffe`

### ISSUE THREAD

**Issue by GiorgioG** [giraffe-fsharp/Giraffe#170]
After installing the Giraffee template and attempting to run 'dotnet new giraffe' I get the following
 

> C:\projects\Project1>dotnet new giraffe
> Usage: new [options]
> 
> Options:
>   -h, --help          Displays help for this command.
>   -l, --list          Lists templates containing the specified name. If no name is specified, lists all templates.
>   -n, --name          The name for the output being created. If no name is specified, the name of the current directory is used.
>   -o, --output        Location to place the generated output.
>   -i, --install       Installs a source or a template pack.
>   -u, --uninstall     Uninstalls a source or a template pack.
>   --type              Filters templates based on available types. Predefined values are "project", "item" or "other".
>   --force             Forces content to be generated even if it would change existing files.
>   -lang, --language   Specifies the language of the template to create.
> 
> 
> **Giraffe Web App (F#)
> Author: David Sinclair and contributors
>     (No Parameters)**
> 
> C:\projects\Project1>

Nothing is created in the current directory.  What am I doing wrong?

**Comment by GiorgioG** [comment]
Solved my problem, I had to use the following command "dotnet new giraffe -lang F#"

This feels like a bug in the tool chain but I'm not sure where to file it.

`dotnet --info
.NET Command Line Tools (2.1.2)

Product Information:
 Version:            2.1.2
 Commit SHA-1 hash:  5695315371

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.2\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.3
  Build    : a9190d4a75f4a982ae4b4fa8d1a24526566c69df
`

**Comment by TheAngryByrd** [comment]
Just file it where in one of the microsoft repos, they'll move it if needed.
