### ISSUE TITLE
Configuration section returns null

### ISSUE THREAD

**Issue by vasily-kirichenko** [giraffe-fsharp/Giraffe#171]
I found this example https://github.com/giraffe-fsharp/Giraffe/blob/master/samples/SampleApp/SampleApp/Program.fs#L75, but it does not work in my project
```fsharp
let configuration = ctx.GetService<IConfiguration>()
let section = configuration.GetSection "Main"
```
and `section.Value` is always `null`.
`appsettings.json` is
```json
{
  "Main": {
      "ApiVersion": "1.0.2",
      "Hosts": [
          "1"
      ]
  }
}
```

Do I need to turn handling `appsettings.json` in some special way or something?

**Comment by gerardtoconnor** [comment]
Hi Vasily, For all services used, need to added in configureServices as asp.net core takes a light explicit approach of adding only service you need, nothing is really added implicitly.

**Comment by vasily-kirichenko** [comment]
@gerardtoconnor What service should I add in `configureServices`?

**Comment by vasily-kirichenko** [comment]
I'm trying this

![image](https://user-images.githubusercontent.com/873919/33838998-1c3d60ea-dea2-11e7-8ac6-11589213f1b4.png)

There is no `AddJsonFile` in `IConfigurationBuilder` interface.

**Comment by gerardtoconnor** [comment]
fun fun with asp.net ...

```fsharp
 let config = new ConfigurationBuilder()
            .AddJsonFile("appsettings.json", optional: false)
            .Build()

WebHostBuilder()
    .UseConfiguration(config)
    ...
```

**Comment by vasily-kirichenko** [comment]
It finally works... I tried to get an json object as string, should be `config.["foo"].Get<a cli mutalble type>()`.

Thanks!

**Comment by Trigun27** [comment]
But how i can inject here IHostingEnvironment to build different variables for different environments? thanks

**Comment by dustinmoris** [comment]
@Trigun27 Do you mean that you want to load a different `appsettings.json` based on environment? You can do this by [naming your settings file something like `appsettings.Development.json`](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/environments?view=aspnetcore-2.1#configuration-by-environment).

**Comment by Trigun27** [comment]
Exactly. Only how to do it programmatically. App starts for different environments and i need to choose different appsettings.{env.EnvironmentName}.json : development, staging and production.

I found method _ConfigureAppConfiguration_. It consumes lambda and seems it works.

```fsharp
let configureEnvironmentVariables (ctx:WebHostBuilderContext) (config: IConfigurationBuilder) =
    let env = ctx.HostingEnvironment.EnvironmentName
    config
        .AddJsonFile("appsettings.json", false, true)
        .AddJsonFile("appsettings." + env + ".json", true) 
        .AddEnvironmentVariables()
        |> ignore

[<EntryPoint>]
let main _ =
   WebHost.CreateDefaultBuilder()
        .UseKestrel()
        .UseContentRoot(contentRoot)
        .ConfigureAppConfiguration(configureEnvironmentVariables)
...

Another approach is: get host and then get EnvironmentName from settings
```fsharp

let host = WebHost.CreateDefaultBuilder()
let env = host.GetSetting("environment")

```
From my point of view, this is not entirely obvious. Can write it in the documentation?
