### ISSUE TITLE
`routef` does not work on %d format specifiers

### ISSUE THREAD

**Issue by vasily-kirichenko** [giraffe-fsharp/Giraffe#172]
`routef "/api/%s/%s"` matches OK, but `routef "/api/%d/%d"` does not. Is it a known issue? /cc @forki

**Comment by gerardtoconnor** [comment]
%d is for int64 in routef , are you looking for int32? That is %i .
String matches should be last in a group after numbers as strings  always match on regex

**Comment by forki** [comment]
routef was broken for me completely 
so I moved to tokenrouter.

**Comment by vasily-kirichenko** [comment]
@gerardtoconnor `%i` works OK. However, it's kind of a subtle behavior imho. 
@forki :(

**Comment by forki** [comment]
@vasily-kirichenko yes it should at least give a type error. but it does not.

**Comment by gerardtoconnor** [comment]
This was a pre-existing convention but basically, issue is that there is no explicit format char for int64, with both %i & %d infering a type of int32 but if being used in printf, accepting both int32 & int64. Not sure how Suave manages to parse int64 but we need to use existing Printf format chars or there will be IDE & compile error.

**Comment by dustinmoris** [comment]
Yes, I think if I remember correctly [Suave always converts into int64 and later converts into an int32](https://github.com/SuaveIO/suave/blob/master/src/Suave/Sscanf.fs#L52) based on the actual parameter type. We *could* do the same, but I thought it might be better if a user can explicitly define via %d and %i which one to use, so there's only one conversion happening overall. I think my preferred suggestion would be to leave it as it is (it's documented this way as well) and perhaps file a suggestion for the F# language to add a format char for int64s... ?

**Comment by gerardtoconnor** [comment]
I hate unneeded work being done so would be great if we could get a new explicit char introduced or figure out some other way to extend without needing waste of heavy int64 parse when only int32 needed

**Comment by forki** [comment]
IMHO It's not really important how suave does it.
It's jsut a sign that type inference is not working correctly here. It would be fine it it would not compile...
