### ISSUE TITLE
dotnet new giraffe requires -lang F# option

### ISSUE THREAD

**Issue by jussimattila** [giraffe-fsharp/Giraffe#173]
Hi,

I have previously created a Giraffe project using `dotnet new giraffe` succesfully. Last night I installed Visual Studio 15.5.1 and this morning `dotnet new giraffe` failed. The command showed help and Giraffe Web App (F#) but nothing was created in the folder:
```
GIT {~\D\G\Funct [master +0 ~0 -1]> dotnet new giraffe --help
Usage: new [options]

Options:
  -h, --help          Displays help for this command.
  -l, --list          Lists templates containing the specified name. If no name is specified, lists all templates.
  -n, --name          The name for the output being created. If no name is specified, the name of the current directory is used.
  -o, --output        Location to place the generated output.
  -i, --install       Installs a source or a template pack.
  -u, --uninstall     Uninstalls a source or a template pack.
  --type              Filters templates based on available types. Predefined values are "project", "item" or "other".
  --force             Forces content to be generated even if it would change existing files.
  -lang, --language   Specifies the language of the template to create.


Giraffe Web App (F#)
Author: David Sinclair and contributors
    (No Parameters)
```
Before trying to issue the command, I was required to re-install the templates even though I had them installed before the VS update. After trying all sorts of things I finally tried with 'dotnet new giraffe -lang F#' and that succeeded:
```
GIT {~\D\G\Funct [master +0 ~0 -1]> dotnet new giraffe -lang F#
The template "Giraffe Web App" was created successfully.

``` 
Maybe this is just my environment, but it was quite annoying and not according to the documentation, so I thought better let you know. My `dotnet` version is 2.1.2.

**Comment by gerardtoconnor** [comment]
This would appear outside our direct control, this is an update to the dotnet cli which would appear to assume all implicit `new` commands are c# unless `-lang f#` explicitly provided. We can probably chase this up with VS team and see if they can provide further insight. @cartermp

**Comment by dustinmoris** [comment]
This must have changed in `dotnet new`, because I am 100% confident that previously you didn't have to specify the `-lang` parameter. I think this is probably a regression bug with `dotnet new` and we should file in the [dotnet cli repository](https://github.com/dotnet/cli), because it would make totally sense that if a template only supports a single language that the `dotnet new [template]` command should pick it by default.

**Comment by cartermp** [comment]
This is indeed a new change, as in [my blog post](https://blogs.msdn.microsoft.com/dotnet/2017/09/26/build-a-web-service-with-f-and-net-core-2-0/) I instruct people to type:

`dotnet new giraffe -o GiraffeSample`

So an issue on the CLI would be the right thing.

**Comment by dustinmoris** [comment]
Done: https://github.com/dotnet/cli/issues/8257

**Comment by dustinmoris** [comment]
Root issue in dotnet/templating has been closed.
