### ISSUE TITLE
Allow deserialization to unit

### ISSUE THREAD

**Issue by cmeeren** [giraffe-fsharp/Giraffe#175]
Newsonsoft.Json can deserialize `null` or the empty string `""` to unit without any problems. However, Giraffe's `BindModelAsync` throws `System.MissingMethodException: 'No parameterless constructor defined for this object.'`

I'd like to be able to deserialize to `unit` in order to avoid having to special-case functions that do not accept a model (these take `unit` instead).

**Comment by gerardtoconnor** [comment]
Can you give us an example of the structure you are serializing with `unit` in it? `unit`, like `void` signifies no bound return value from an expression so might help if we can see data as all expressions should be evaluated by time of serialization and the absence of data can usually be expressed in many ways.

**Comment by cmeeren** [comment]
First a bit of background:

The functions that represent my API endpoints (my usecases, if you will) do not know anything about Giraffe or any other framework. They have the following signature:

```f#
'requestArgs -> Async<Result<'a, 'b>>
```

where `'requestArgs` is normally a record type containing the parameters for the API endpoint, for example:

```f#
type SignInArgs =
  {User: string
   Pwd: string}
```

This is defined in a separate type like this to make it easy for the accompanying mobile app to use the API - it simply creates a `SignInArgs`, serializes it, and sends it as the body of a POST request to the API.

My API routes are set up like:

```f#
POST >=> route "/api/signin" >=> handle signIn
POST >=> route "/api/register" >=> handle register
```

where `signIn` and `register` are functions with the signature above, and `handle` is defined like this:

```f#
let handle (handler: 'args -> Async<Result<'a,'b>>) : HttpHandler = 
  fun next ctx ->
    task {
      let! args = ctx.BindModelAsync<'args>()
      let! response = handler token
      return! json response next ctx
    }
```

(Yes, I'm serializing and sending a `Result` type. This seems fine because the only API client is a Xamarin app I'm developing using F#, and it saves some conversion boilerplate.)

Now, to the point: Not all of my endpoints actually accept parameters. For example, `/api/getTaskList` simply gets the list of tasks and is not parametrized by anything. So in this case, `'requestArgs` in my usecase function is `unit`. But Giraffe won't deserialize to unit, so currently I'm creating dummy classes (`type TaskListArgs() = class end`).

Did that answer your question?

**Comment by JonCanning** [comment]
If you have F# both ends, could you use DUs?

```
type Request = 
| SignIn of SignInArgs
| Register of RegisterArgs
| GetTaskList

type Response = 
| Tasks of Task array
| Failure
```

Then you only have one route and the handler pattern matches the `Request` and returns a `Response`?

```
let handle next ctx = 
    task {
      let! request = ctx.BindModelAsync<Request>()
      let! response =
        match request with
        | SignIn signInArgs -> signIn signInArgs
        | Register registerArgs -> register registerArgs
        | GetTaskList -> fetchTasks()
      return! json response next ctx
    }
```

**Comment by cmeeren** [comment]
That's actually not a bad idea. I'll have to think on that for a bit.

Regardless, since Giraffe uses Newtonsoft.Json under the hood, I'd expect it to be able to serialization and deserialize the same kinds of objects.

**Comment by lambdakris** [comment]
Isn't the `System.MissingMethodException: 'No parameterless constructor defined for this object.'` error typically because you need to decorate your type with a [<CLIMutable>] attribute? 

It looks like the various .Bind... HttpContext extension methods use the generic data binding technique where you create an instance of the generic type with a parameterless constructor and populate the fields of the type using reflection. This would mean that you need the CLIMutable attribute so that the "create an instance of the generic type with a parameterless constructor" part works...

**Comment by gerardtoconnor** [comment]
Jon's suggestion is nice and will lead to less bugs down the line as you are domain modelling all permutations explicitly ... but in the end I would have concern you are over abstracting here as you know before the handle function is called which case it is and therefore, your binding of model needlessly for `GetTaskList` when no model really to bind. All your handle Fn seems to be doing is shortcut to bind JSON to model, apply Fn and respond with JSON.... signIn and register fns could have helped to wrap, task list could just call >> JSON.

**Comment by gerardtoconnor** [comment]
@cmeeren is there anything further you need on this or can we proceed to close?

I think the general gist is: 
- don't over abstract
- model domain more explicitly
- if you are serializing `unit`, data structure needs review as `unit` represents an empty expression

**Comment by cmeeren** [comment]
I'm good, closing. Thanks for suggestions!
