### ISSUE TITLE
SampleApp: HttpContext::SignInAsync doesn't appear to be supported anymore

### ISSUE THREAD

**Issue by bizmonger** [giraffe-fsharp/Giraffe#183]
In the SampleApp, HttpContext::SignInAsync doesn't appear to be supported anymore.
However, people such as myself rely on this sample project for guidance on how to use the Giraffe framework.

In conclusion, what is the alternative to using HttpContext::SignInAsync ?

**Giraffe: v0.1.0-beta-500**

Example:
```
let loginHandler =
    fun (next : HttpFunc) (ctx : HttpContext) ->
        task {
            let issuer = "http://localhost:5000"
            ...
            let identity = ClaimsIdentity(claims, authScheme)
            let user     = ClaimsPrincipal(identity)
            
            do! ctx.SignInAsync(authScheme, user)
            
            return! text "Successfully logged in" next ctx
        }
     
```

**Comment by dustinmoris** [comment]
What do you mean it isn't supported anymore? Did ASP.NET Core deprecate it? This is an extension method which comes from `Microsoft.AspNetCore.Authentication.AuthenticationHttpContextExtensions` and you need to add the relevant NuGet packages for it.

**Comment by dustinmoris** [comment]
Please check [Using Cookie Authentication without ASP.NET Core Identity
](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/cookie?tabs=aspnetcore2x) for detailed info.

**Comment by bizmonger** [comment]
I never considered that. Thanks. It compiles now.
