### ISSUE TITLE
Running tests on mono-net461

### ISSUE THREAD

**Issue by TheAngryByrd** [giraffe-fsharp/Giraffe#190]
`dotnet test` is broken on mono (https://github.com/Microsoft/vstest/issues/1318) but if we use `dotnet-xunit` I added support for mono a while ago.  We had this discussion previously in https://github.com/giraffe-fsharp/Giraffe/pull/58 but seems like it's not in beta anymore so this may be worth considering.  Thoughts?

**Comment by dustinmoris** [comment]
I'm up for `dotnet xunit` if it solves the issue!
