### ISSUE TITLE
Huge unmanaged memory leak running on IIS

### ISSUE THREAD

**Issue by vasily-kirichenko** [giraffe-fsharp/Giraffe#198]
So I have a simple Giraffe server, which has a number of Akka actors running in it. It works totally OK being run locally as a console app, no memory leaks at all. I deployed it to IIS and mentioned that dotnet process quickly eats memory (it takes it about 5 minutes to grab 2GB starting from 150MB), after that IIS kills it (AFAIK) and start a new process. 

Profiling with dotMemory showed that unmanaged memory is the problem:

![image](https://user-images.githubusercontent.com/873919/34437124-a8ae2b5a-ecac-11e7-9e12-f2dcbaf13a8c.png)

Before that there was no Akka in the server and there was no memory leaks at all.

Although it seems to be more related to Akka (and long running processes inside IIS hosted services in general), I'm appreciate any help from you guys as you are much more experienced in all this stuff than me. Thanks!

**Comment by forki** [comment]
what was the solution?

**Comment by vasily-kirichenko** [comment]
It seems that's how IIS manages memory. After removing every 5 minutes pool recycling policy it almost stop eating the memory and was 2.6GB after running for an hour. I will see what it looks like tomorrow. 

Anyway, all the memory was unmanaged, so it looks like a pre-allocation that does Core if it sees a lot of free memory (~60GB in my case).

**Comment by yBother2** [comment]
Have the very same problem with IIS but regular recycling is turned off. After a month I already have 7gb+ unmanged memory. dunno how to address this issue...

**Comment by dustinmoris** [comment]
God that sounds awful. Sorry I my days of running anything inside IIS are well in the past.
