### ISSUE TITLE
Error in task builder with .NET Core 2

### ISSUE THREAD

**Issue by ian-moore** [giraffe-fsharp/Giraffe#203]
I am upgrading some code to .NET Core 2 (on sdk 2.1.3)

I have the following function:
```
let handleAsyncResult (okFunc: 'a -> HttpHandler) (errorFunc: 'b -> HttpHandler) (ar: Async<Result<'a,'b>>) =
    fun next ctx -> task {
        let! r = ar
        match r with
        | Ok v -> 
            return! okFunc v next ctx
        | Error ex -> 
            return! errorFunc ex next ctx
    }
```

Which results in the following run time error:
```
fail: Giraffe.Middleware.GiraffeErrorHandlerMiddleware[0]
      An unhandled exception has occurred while executing the request.
System.MissingMethodException: Method not found: 'System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1<System.__Canon> System.Threading.Tasks.Task`1.ConfigureAwait(System.Boolean)'.
   at [**redacted**].handleAsyncResult@75.Invoke(Unit unitVar)
   at Giraffe.TaskBuilder.run[a](FSharpFunc`2 firstStep)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Giraffe.HttpHandlers.chooseHttpFunc@94.Invoke(Unit unitVar)
   at Giraffe.TaskBuilder.run[a](FSharpFunc`2 firstStep)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Giraffe.Middleware.Invoke@39.Invoke(Unit unitVar)
   at Giraffe.TaskBuilder.run[a](FSharpFunc`2 firstStep)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Giraffe.Middleware.Invoke@64-7.Invoke(Unit unitVar)
   at Giraffe.TaskBuilder.tryWith[a](FSharpFunc`2 step, FSharpFunc`2 catch)
```

Can't seem to pin down if this is a problem in the library or I have somehow made a bad task - opening an issue in case this has come up before or some debugging guidance. Apologies if this issue belongs on the Giraffe.Tasks repo.

**Comment by TheAngryByrd** [comment]
I just looked and it doesn't appear we have any tests around `Async<'a>` in  https://github.com/giraffe-fsharp/Giraffe.Tasks/blob/master/tests/Giraffe.Tasks.Tests/TasksTests.fs

I'll try to reproduce there.

**Comment by gerardtoconnor** [comment]
Thanks Jimmy, this is an interesting one, looks like bind overload not recognizing Async, Ian, might be worth testing if Async.AwaitTask works on ar?

**Comment by ian-moore** [comment]
@gerardtoconnor indeed, I tried `let! = Async.StartAsTask ar` and get the same error

**Comment by TheAngryByrd** [comment]
Is there any particularly interesting about that `Async<'a>` ?  I can't seem to reproduce with some tests.

**Comment by ian-moore** [comment]
Not sure what would qualify as "interesting". I'll keep digging

**Comment by ian-moore** [comment]
Ok, I've narrowed this down when running against the `Giraffe.Tasks` source. I have a `do!` that is resulting in a faulted task and the actual error (in my application code) was getting swallowed in there before being thrown.

Is there I can get that error surfaced from `Binder<>.GenericAwait`, or should `do!` always be used in a try block?

**Comment by gerardtoconnor** [comment]
@ian-moore can you try bind with 
```
let! _ = expr
```
Instead of do! ... i think @forki encountered this binding on do! Also

**Comment by ian-moore** [comment]
I tried to reproduce this outside of my project in a clean template and wasn't able to. Farthest I was able to get was that `return!` and `do!` only worked when using GenericAwait instead of GenericAwaitConfigureFalse. Not sure if that provides any insight or not.

I will close this task until I have better details as I'm going to try re-working some things instead of troubleshooting further.

**Comment by gerardtoconnor** [comment]
we're always interested on fixing these edge cases so do let us know how you get on, thanks for reporting this.
