### ISSUE TITLE
Nested task ce issue with htmlFile when hosted on IIS

### ISSUE THREAD

**Issue by lambdakris** [giraffe-fsharp/Giraffe#215]
## Description
I am having one of those seemingly async related issues with an app I deployed to an IIS server.

It is simply the use of the htmlFile handler, something like so...
```
route "/example" >=> htmlFile "wwwroot/example.html"
```
It runs fine when debugging or when launching from dotnet cli, but when I deploy it to an IIS server I begin to get the following exception:
```
System.UnauthorizedAccessException: Access to the path 'C:\inetpub\wwwroot\Example\wwwroot\example.html' is denied.
``` 
I have the wwwroot setup so that it is available both when running locally and when deployed and I have made sure it is not a path issue as you will see if you look at my analysis below

## The short analysis
I believe the issue stems from the interaction between the task computation(s) used within the htmlFile handler and how the FileStream object is initialized. Specifically, [line 22 in Common.fs](https://github.com/giraffe-fsharp/Giraffe/blob/master/src/Giraffe/Common.fs#L22) is insufficient for a situation where it is used from a nested task ce...probably because the FileShare mode is not set to read yet it gets read from the containing task while it has not yet been release from the nested task...?

## The long analysis
In case it provides anyone with something important, this is what I looked into.

Taking a guess that the issue had to do with async, I wrote a couple of variations of the logic within the [htmlFile handler](https://github.com/giraffe-fsharp/Giraffe/blob/master/src/Giraffe/HttpHandlers.fs#L341) and the [readFileAsStringAsync function](https://github.com/giraffe-fsharp/Giraffe/blob/master/src/Giraffe/Common.fs#L20) from scratch so that I could isolate the effects.

The following works (notice that everything happens inside a single task ce)
```
...
task {
    use stream = new FileStream(filePath, FileMode.Open)
    use reader = new StreamReader(stream)
    let! content = reader.ReadToEndAsync()
    return! html content next context
}
...
```
The following DOES NOT work (notice that the io ops are in a nested task ce)
```
...
task {
    let! content = task {
        use stream = new FileStream(filePath, FileMode.Open)
        use reader = new StreamReader(stream)
        return! reader.ReadToEndAsync()
    }
    return! html content next context
}
...
```
The following DOES work (notice that the io ops are still in a nested task ce but there is no explicit FileStream)
```
...
task {
    let! content = task {
        use reader = new StreamReader(filePath)
        return! reader.ReadToEndAsync()
    }
    return! html content next context
}
...
```
The following also works (notice that the io ops are still in a nested task ce but we have explicitly set the FileAccess and FileShare parameters in addition to the FileMode)
```
...
task {
    let! content = task {
        use stream = new FileStream(filePath, FileMode.Open, FileAccess.Read, FileShare.Read)
        use reader = new StreamReader(stream)
        return! reader.ReadToEndAsync()
    }
    return! html content next context
}
...
```

From the above, I surmise that the differentiator is how the FileStream object is initialized

## Proposed fix(es)
There are two possible fixes
1. Replace https://github.com/giraffe-fsharp/Giraffe/blob/master/src/Giraffe/Common.fs#L22 with
`use stream = new FileStream(filePath, FileMode.Open, FileAccess.Read, FileShare.Read)`
2. Remove https://github.com/giraffe-fsharp/Giraffe/blob/master/src/Giraffe/Common.fs#L22 entirely and replace the next line `use reader = new FileReader(stream)` with `use reader = new FileReader(filePath)`, letting the reader manage it's own internal file stream

* Out of curiosity I went ahead and tried setting useAsync to true (available in overload 12), 
`FileStream("wwwroot/openlayers.html", IO.FileMode.Open, IO.FileAccess.Read, IO.FileShare.Read, bufferSize = 4096, useAsync = true)`, which works, but I could not immediately come up with a way to contrast the performance. Based on the [dotnet docs](https://docs.microsoft.com/en-us/dotnet/api/system.io.filestream.-ctor?view=netframework-4.7.1#System_IO_FileStream__ctor_System_String_System_IO_FileMode_System_IO_FileAccess_System_IO_FileShare_System_Int32_System_Boolean_), it seems it would only be helpful for large html files, but how large is large I don't know. I also wonder whether there is any interplay between setting the useAsync parameter to true and the behaviour of the ReadToEndAsync method. Further, I wonder if the same thing that is true for useAsync is true for ReadToEndAsync, as in, it is better left for large files, otherwise one would ultimately get better throughput if one were to use the sync method?

**Comment by dustinmoris** [comment]
Hi, thanks for this great bug report and the analysis! In 2. you probably meant to replace the second line with the `StreamReader`, because I don't know of any `FileReader`, correct?

I think 2. is a sensible approach. I think 1. and 2. are technically equivalent, but 2. maybe slightly more elegant as it has less code.

Generally the `StreamReader` is used for reading text content and `FileStream` for binary content, hence why there is also some extra parameter for `useAsync`. It is also interesting that [the default has been set to `false`](https://github.com/dotnet/corefx/pull/8642) on purpose. I think it's probably safer to keep it this way and use the `StreamReader` anyways.

**Comment by dustinmoris** [comment]
Maybe it's because it's late for me today, but something else is extremely confusing...

The docs and my code both show the constructor to require a `StringSegment`: https://docs.microsoft.com/en-us/dotnet/api/microsoft.net.http.headers.entitytagheadervalue.-ctor?view=aspnetcore-2.0

However, the linked file from above doesn't... also the namespaces are different:
`Microsoft.Net.Http.Headers` vs `System.Net.Http.Headers`??

Does the same class exist in two different namespaces and looks different?

**Comment by lambdakris** [comment]
@dustinmoris heh, yeah, `StreamReader` is what I was going for. After reading the corefx issue you pointed to, https://github.com/dotnet/corefx/pull/8642, it does sound like using StreamReader by itself might be a good default since it delegates the specifics of how best to initialize/manage the FileStream to the platform. I'd be happy to submit a PR.

**Comment by lambdakris** [comment]
@dustinmoris do you prefer to close issues when the PR is accepted or when a release with the PR is published?

**Comment by dustinmoris** [comment]
Oh I did miss this message.. yeah I will close this issue when the fix goes out!

**Comment by dustinmoris** [comment]
This went out today with `Giraffe 1.0.0`.
