### ISSUE TITLE
Can a SubRouteF concept work?

### ISSUE THREAD

**Issue by TWith2Sugars** [giraffe-fsharp/Giraffe#220]
I found my self in a situation using saturnframwork where I needed to "forward" to a url such as "/api/%i"
I started to add forwardf to saturn by looking at how forward was implemented and realized it ultimately called subRoute.

I couldn't find an existing subRouteF functions and I attempted to add it my self (by seeing how subroute and route/routef work) but I really have no idea what I'm doing.

Is this even possible in how giraffe works?

**Comment by gerardtoconnor** [comment]
Hi,

A subRoute is just a common url stub for a collection of routes with the same prefix eg `/api/`

If you want to have a `/api/%i` that will parse after the api, and only one route is using this pattern, it's just a route(f), not a subroute as there is no grouping. If you are grouping routes please provide some examples but from above, and in general, `subRouteF` doesn't make sense as you cannot group routes by a prefix that is unknown (the unknown format parser)

**Comment by TWith2Sugars** [comment]
I see, that makes sense. The issue is really down to how I structure my app.

Overall I'm attempting to get [saturn's forward](https://github.com/SaturnFramework/Saturn/blob/master/sample/Saturn.Sample/Saturn.Sample.fs#L134) to work like it's getf. I'll create an issue there and see if I can figure out to work it.

**Comment by gerardtoconnor** [comment]
If you are parsing the argument directly after api, instead of having more child routes that you probably do not want to use the "forward" but instead, just a plain `getf` as is is just one routing function, not many.

**Comment by dustinmoris** [comment]
In #223 someone had actually a valid use case for `subRoutef`. A `subRoutef` http handler has now been added and will be released with the next version of Giraffe.

**Comment by TWith2Sugars** [comment]
Thanks! I was getting no where trying to add it in saturn.

**Comment by TWith2Sugars** [comment]
Do you have a roadmap for when the next version is released?

**Comment by dustinmoris** [comment]
I am aiming for some point this week!
