### ISSUE TITLE
How implement token based auth (no OAUTH)

### ISSUE THREAD

**Issue by mamcx** [giraffe-fsharp/Giraffe#221]
I need to support basic token auth, similar to:

https://getblimp.github.io/django-rest-framework-jwt/#rest-framework-jwt-auth

I will use JWT to store data and to authenticate, but not to use OAuth or a external provider (all the examples I found are like that).

The token will be generated based in a username/pass (for humans) and app_id/app_key (for APIs). I already have solved this part, but not understand how plug into giraffe.

**Comment by TheAngryByrd** [comment]
Have you looked at https://github.com/giraffe-fsharp/Giraffe/blob/master/samples/JwtApp/JwtApp/Program.fs ?

**Comment by mamcx** [comment]
Is the use of :

```
let jwtBearerOptions (cfg : JwtBearerOptions) =
    cfg.SaveToken <- true
    cfg.IncludeErrorDetails <- true
    cfg.Authority <- "https://accounts.google.com"
    cfg.Audience <- "your-oauth-2.0-client-id.apps.googleusercontent.com"
    cfg.TokenValidationParameters <- TokenValidationParameters (
        ValidIssuer = "accounts.google.com"

```
mean that it delegate to google the auth? I don't wanna to do that. I do the auth myself.

**Comment by mamcx** [comment]
I found the sample I need at:

https://medium.com/@dsincl12/json-web-token-with-giraffe-and-f-4cebe1c3ef3b

**Comment by dustinmoris** [comment]
Great that you could resolve your question. I'll add the blog post to the README as well.
