### ISSUE TITLE
Abandoning Giraffe.Tasks in Giraffe 1.0 broke all our Task workflows

### ISSUE THREAD

**Issue by forki** [giraffe-fsharp/Giraffe#222]
![image](https://user-images.githubusercontent.com/57396/36018112-d43f66a0-0d7a-11e8-8c2a-b2613af6fef1.png)

![image](https://user-images.githubusercontent.com/57396/36018120-d9569668-0d7a-11e8-81a1-39ad1a2f80ea.png)

I don't think it was a good idea to abandon the project and to go something that is missing a lot of patches.

**Comment by gerardtoconnor** [comment]
Did not know we were abandoning Giraffe.Tasks, we lose control to fix issues by changing dependency to static TaskBuilder.fs .

TaskBuilder.fs is not perfect and now bakes limitations into platform going forward, not sure why this was not discussed before release.

**Comment by TheAngryByrd** [comment]
I'm also surprised we didn't release a 1.0.0-betaxxx to allow testing of these many changes.

**Comment by forki** [comment]
`open FSharp.Control.Tasks.ContextInsensitive` seems to work for this particular issue
