### ISSUE TITLE
Is there a cleaner way to compose with routef?

### ISSUE THREAD

**Issue by Lanayx** [giraffe-fsharp/Giraffe#223]
In the sample file there are lines

```
let showUserHandler id =
    mustBeAdmin >=>
    text (sprintf "User ID: %i" id)
```

https://github.com/giraffe-fsharp/Giraffe/blob/master/samples/SampleApp/SampleApp/Program.fs#L71-L73

So _mustBeAdmin_ filter moves from all routes configuration to particular handler. Is there a better way to have both _routef_ and _mustBeAdmin_ composed together like _route_  routes?

**Comment by dustinmoris** [comment]
Hi,

Yes, you could also do this:

```fsharp
let webApp =
    mustBeAdmin >=> choose [
        routef "/....." handler1
        routef "/....." handler2
    ]

**Comment by Lanayx** [comment]
In my app I want to have some routes secured and some not, just like in the sample app, so I want to apply mustBeAdmin on route basis. And this works fine with _route_, but not fine with _routef_

**Comment by dustinmoris** [comment]
Ok I understand... can you give me a more concrete example. The `routef` handler has obviously a dynamic element where some part of the route is whatever a user has typed into a URL. You could use `subRoute` or `routeStartsWith` in combination with an auth handler before all routef handlers:

```

**Comment by dustinmoris** [comment]
This is another example:

```fsharp
let webApp : HttpHandler =
    choose [
        // Not secured
        route "/"    >=> text "Hello"
        route "/foo" >=> text "Bar"

        // Secured without subRoute
        mustBeLoggedIn >=>
            choose [
                route "/user/"    >=> text "Hello"
                route "/user/foo" >=> text "Bar"
            ]

        // Secured with subRoute
        subRoute "/secure" (
            mustBeLoggedIn >=>
                choose [
                    routef "/%s"    handler1
                    routef "/%s/%i" handler2
                ]
        )
    ]
```

**Comment by Lanayx** [comment]
So, here is the sample, I want this urls:
_/en/articles/top_
_/en/article/123_
to be public and this url
_/en/dashboard_
to be private
I was planning to have such rules:
```
routef "/%s/articles/top" getTopArticles
routef "/%s/articles/%s" getArticle
routef "/%s/dashboard" >=> authorize >=> getDashboard
```
Is there a way to implement this?

**Comment by Lanayx** [comment]
I see, looks like you mean that I need to exchange _authorize_ and _routef_?

**Comment by Lanayx** [comment]
I think that there is one issue there. If user enteres the wrong url, it will go through the authorization step first, which includes database interaction, while it could be just rejected by the wrong url. I think urls check should go before the user verification.

**Comment by dustinmoris** [comment]
Right.. because you have a dynamic `%s` at the very beginning of your route I think you are better by having the authorize inside the handler like shown in the first example which you referred to.

To be fair this is the first use case where I see how a `subRouteF` could make sense... let me think about it and perhaps I'll try to implement something which can make this more elegant for you, but for now go with it like shown in the sample app.

**Comment by Lanayx** [comment]
Ok, thank you for the response

**Comment by dustinmoris** [comment]
I have added a `subRoutef` http handler which will be available with the next release.

See [subRoutef](https://github.com/giraffe-fsharp/Giraffe/blob/develop/DOCUMENTATION.md#subroutef)

**Comment by Lanayx** [comment]
Thank you! But looks like there will still be no way to silently pass the lang argument further in the compose pipe. I'm just comparing it with asp.net mvc were you just put [Authorize] attribute regardless of the route, but the workaround in your example looks sufficient, at least for now I don't think the surrounding function can become too complex.

**Comment by dustinmoris** [comment]
You can do this now:

```fsharp
let webApp : HttpHandler =
        subRoutef "/%s" (fun lang ->
            choose [
                subRoute "/articles" (
                    choose [
                        route "/top" >=> getTopArticles lang
                        routef "/%s" (getArticle lang)
                    ])
                route "/dashboard" >=> authorize >=> getDashboard lang
            ]
        )
```

**Comment by dustinmoris** [comment]
But, if you don't want to pre-parse the first parameter, there is another option which will work as well. For actually a very different reason (trailing slash handling) I have just finished implementing a `routex` handler: https://github.com/giraffe-fsharp/Giraffe/blob/develop/DOCUMENTATION.md#routex

With that you could check the route is correct before doing authorize and then use the full `routef` path for silent parameter passing:

```fsharp
let webApp : HttpHandler =
    choose [
        routef "/%s/articles/top" getTopArticles
        routef "/%s/articles/%s" getArticle
        routex "/[a-z]{2}/dashboard" >=>
            authorize >=> routef "/%s/dashboard" getDashboard
    ]
```

What do you think?

**Comment by Lanayx** [comment]
You are right, I wanted to be less verbose and don't specify lang parameter in the route configuration code. For example I could also have private route /en/my-articles/123 with route **/%s/my-articles/%s**, so this will introduce more nested functions. The solution with routex looks more attractive for me, however I'm a bit worried about performance if regex is used there =)

**Comment by dustinmoris** [comment]
Fair enough :). The regex is compiled so should be considerably faster than normal, but I understand your concerns. Unfortunately this is the best I can offer for now.

**Comment by Lanayx** [comment]
I see, thank you for such quick cooperation anyway!
