### ISSUE TITLE
Impossible to use let! with Async-returning functions inside task CE since 1.0.0

### ISSUE THREAD

**Issue by cmeeren** [giraffe-fsharp/Giraffe#225]
Just upgraded to 1.0.0, and can't compile. It seems it's suddenly impossible to use

```f#
task {
  let! x = functionReturningAsync()
}
```

The error I get is `The type Async<snip> is not compatible with the type Task<snip>`.

I know you've moved from your own internal TaskBuilder.fs to [Robert Peele's version](https://github.com/rspeele/TaskBuilder.fs), and that any questions regarding TaskBuilder.fs belongs there, but I'm wondering if this change in Giraffe functionality was intended on your part.

If it was, then I (and I expect I'm not alone) need to either
* switch all my `async` CEs to `task` CEs, which I'm loath to do because I want to stick to vanilla F# as far as possible and don't want requirements from application frameworks like Giraffe to leak into my core code (and it would also mean I need to rewrite an `asyncResult` CE I'm using to `taskResult`), or
* edit the highest-level `Async`-returning functions (used in the `task` CEs in my Giraffe project) to return `Task` using `Async.StartAsTask`, which I'd also rather not do for the same reason (and I don't know if this has any other side effects compared to using the `task` CE everywhere).

**Comment by dustinmoris** [comment]
Hi,

Sorry for causing the inconvenience. In Giraffe.Tasks we had an additional overload which did a simple `Async.StartAsTask`, so you could do that now, but I have also openen an issue in TaskBuilder.fs to see if we can get that convenience overload back in again.

I don't quite understand why you would have to change the return type of your highest level Async-returning functions. Could you not just append the `Async.StartAsTask` in your Giraffe code (e.g. at the very last step in a `HttpHandler`)?

**Comment by cmeeren** [comment]
> I don't quite understand why you would have to change the return type of your highest level Async-returning functions. Could you not just append the `Async.StartAsTask` in your Giraffe code (e.g. at the very last step in a `HttpHandler`)?

D'oh 🤦‍♂️ Of course I could. Thanks. :)

**Comment by dustinmoris** [comment]
Ok perfect :)
