### ISSUE TITLE
How return a exception inside a task?

### ISSUE THREAD

**Issue by mamcx** [giraffe-fsharp/Giraffe#226]
I try to write the auth part for generating tokens for my Api:

```
let handlePostToken =
    fun (next : HttpFunc) (ctx : HttpContext) ->
        task {
            let model = 
                try
                   Some(ctx.BindJsonAsync<LoginViewModel>())
                with e -> 
                    None

            match model with
            | Some(x) ->
                // authenticate user
    
                let tokenResult = generateToken x.Email

                return! json tokenResult next ctx
            | _ ->   
                let msg =""
                RequestErrors.BAD_REQUEST msg next ctx
        }
```

But how return that the handle fail? If I put `failwithf` it give me a type mismatch. I try look at the docs and try with `RequestErrors` and is the same

**Comment by dustinmoris** [comment]
You forgot to put a `return!` for returning the request error.

```fsharp
let handlePostToken =
    fun (next : HttpFunc) (ctx : HttpContext) ->
        task {
            let model = 
                try Some (ctx.BindJsonAsync<LoginViewModel>())
                with _ -> None

            match model with
            | Some x ->
                // authenticate user
                let tokenResult = generateToken x.Email
                return! json tokenResult next ctx
            | _ ->   
                let msg =""
                return! RequestErrors.BAD_REQUEST msg next ctx
        }
```

If you want to throw an exception instead (even though this would be less FSharpy) then you can also do `return failwith ""`.

Hope that helps!

**Comment by dustinmoris** [comment]
I'll close this issue as it was only a question, but if you have more questions feel free to re-open again or you can also try to get help in Slack: fsharp.slack.com. More info [here](https://github.com/giraffe-fsharp/Giraffe#contact-and-slack-channel).

**Comment by forki** [comment]
small correction: it's `return! failwith "..."`
you need the bang

**Comment by dustinmoris** [comment]
Thanks @forki :)
