### ISSUE TITLE
Request: Documention on return types other than text/json

### ISSUE THREAD

**Issue by BrianVallelunga** [giraffe-fsharp/Giraffe#228]
How do I go about returning a specific status code from an HttpHandler? For example, I might want to return an Accepted or OK status codes without content. The examples just show using json and text.

Thanks

**Comment by dustinmoris** [comment]
Hi,

You can return other data by using some of the more basic `HttpHandler` functions, which do not set a HTTP `Content-Type` header like [`setBody`](https://github.com/giraffe-fsharp/Giraffe/blob/master/DOCUMENTATION.md#writing-bytes) or [`setBodyFromString`](https://github.com/giraffe-fsharp/Giraffe/blob/master/DOCUMENTATION.md#writing-bytes), which literally just write the specified content to the response stream without adding any other headers other than the `Content-Length` header.

If you want to return a response without a body at all then you can do the following:

```fsharp
let someHandler : HttpHandler =
    fun (next : HttpFunc) (ctx : HttpContext) ->
        ctx.SetStatusCode StatusCodes.Status202Accepted
        Task.FromResult (Some ctx)
```

By returning `Some ctx` you can stop any further processing and return the current response object to the client - which at this point wouldn't have anything written to the response body.

This is [explained in more detail here](https://github.com/giraffe-fsharp/Giraffe/blob/master/DOCUMENTATION.md#httphandler).

In the case of `Accepted` you can also use the [predefined handler](https://github.com/giraffe-fsharp/Giraffe/blob/master/DOCUMENTATION.md#successful) for it:

```fsharp
route "/" >=> Successful.accepted (xml someObj)
```

Hope the linked documentation makes sense. If you have any further questions or a suggestion how to improve the docs don't hesitate to let me know :)

**Comment by BrianVallelunga** [comment]
Thanks for the help. It seems a bit strange that returning text or json and returning just an OK or Accepted don't follow the same pattern (of just calling a function), but this will work.

**Comment by BrianVallelunga** [comment]
The ctx.SetStatusCode method doesn't seem to exist, so maybe I'm missing something. There is a function setStatusCode though. I seem to be able to also do the following:

    let handleWebhookPost =
        fun (next : HttpFunc) (ctx : HttpContext) ->
            task {
               // Do Work Here
                ctx.Response.StatusCode <- StatusCodes.Status200OK
                return Some ctx
            }

**Comment by dustinmoris** [comment]
Most features are mirrored between `HttpContext` extension methods and a `HttpHandler` function.

For example you can return a JSON response through `ctx.WriteJsonAsync` or the `json` http handler.

Just returning an OK does have a function as well, this is where I pointed you to the [status code handlers](https://github.com/giraffe-fsharp/Giraffe/blob/master/DOCUMENTATION.md#successful).

Also there is definitely a [SetStatusCode](https://github.com/giraffe-fsharp/Giraffe/blob/master/src/Giraffe/Core.fs#L78) extension method.

Which version of Giraffe are you using?

**Comment by BrianVallelunga** [comment]
I was using an older version. Thanks for the help getting this working.
