### ISSUE TITLE
Awaiting non-generic task

### ISSUE THREAD

**Issue by alfonsogarciacaro** [giraffe-fsharp/Giraffe#231]
According to the latest blog post, Giraffe now has a dependency on `TaskBuilder`. After upgrading to Giraffe 1.0 the compiler complains with the following error:

![image](https://user-images.githubusercontent.com/8275461/36200592-81246d6a-117d-11e8-9e1e-dc73858e6a83.png)

This is because `CreateDB` returns `Task` instead of `Task<unit>` which makes sense because it belongs to a C# project. However, if I replace the `open Giraffe` statement with `open FSharp.Control.Tasks` then it works. In other files were I only await generic tasks opening Giraffe is enough and I didn't need to touch anything.

Do you know why this happens (the `task` builder is exposed by Giraffe but it doesn't work with non-generic tasks)? Can it be fixed?

**Comment by forki** [comment]
open FSharp.Control.Tasks.ContextInsensitive

**Comment by dustinmoris** [comment]
I'll put a big note in the docs so it's more obvious.

**Comment by alfonsogarciacaro** [comment]
Thanks for the tip, as commented above just `open FSharp.Control.Tasks` works for me.

> BTW, I also took a while until I discover you need to do `services.AddGiraffe()` now or you'll a NRE whenever you use the negotiation helpers, like `OK`, etc... It'll be nice to make that prominent in the docs too.

**Comment by dustinmoris** [comment]
Agreed, have another issues for this already open! Will do in a bit as well!
