### ISSUE TITLE
Issue with plain Task and do!

### ISSUE THREAD

**Issue by garuma** [giraffe-fsharp/Giraffe#232]
A cross-reference from https://github.com/rspeele/TaskBuilder.fs/issues/12

Giraffe by default exports the context insensitive version of TaskBuilder.fs which has the issue that using `do!` on a plain Task doesn't work:

```fsharp
let fooTask = FSharp.Control.Tasks.ContextInsensitive.task

let someOp =
  fooTask {
    do! Task.Delay(4)
  }
```

To workaround the issue for now you have to convert your `Task` into a `Task<unit>` like so:

```fsharp
let toUnitTask (task: System.Threading.Tasks.Task) =
  let emptyContinueWith _ : unit = ()
  task.ContinueWith(emptyContinueWith, TaskContinuationOptions.ExecuteSynchronously)

let someOp =
  task {
    do! toUnitTask (Task.Delay(4))
  }
```

**Comment by dustinmoris** [comment]
If you have do! bindings in your Giraffe web application then you must open the FSharp.Control.Tasks.ContextInsensitive namespace to resolve any type inference issues:

```fsharp
open FSharp.Control.Tasks.ContextInsensitive
```

I have already [documented this in the docs](https://github.com/giraffe-fsharp/Giraffe/blob/develop/DOCUMENTATION.md#tasks), which will be merged to master probably today!
