### ISSUE TITLE
Reponse caching support

### ISSUE THREAD

**Issue by Lanayx** [giraffe-fsharp/Giraffe#235]
Hi! Is there response caching in the roadmap?

https://docs.microsoft.com/en-us/aspnet/core/performance/caching/

Thanks

**Comment by dustinmoris** [comment]
What were you thinking of? The [response caching middleware](https://docs.microsoft.com/en-us/aspnet/core/performance/caching/middleware) should work with Giraffe out of the box. It is a separate ASP.NET Core middleware which you can plug alongside Giraffe. You should add it to the ASP.NET Core pipeline before Giraffe, so that requests can be served from the caching middleware first and only if not possible let Giraffe do the job.

**Comment by Lanayx** [comment]
I'm looking for the same functionality that I get in MVC by setting attribute on action. For functional approach it probably should be an element in a chain like
route >=> auth >=> cache >=> handler

**Comment by BrianVallelunga** [comment]
I'm interested in learning how to compose this as well. The middleware instructions show how to do it in C#, but I'm not sure what the appropriate F# is with `app.Use`

    // Add response caching
    let cacheControl = new CacheControlHeaderValue()
    cacheControl.Public <- true
    cacheControl.MaxAge <- new Nullable<TimeSpan>(TimeSpan.FromSeconds(60.))

    // Not sure about this since it the next delegate is supposed to be called asynchronously
    app.Use(fun context next ->
                context.Response.GetTypedHeaders().CacheControl <- cacheControl
                next() // This isn't right. Does this whole thing need to be in a task or async block?
               ) |> ignore

**Comment by ebi-igweze** [comment]
For composing middleware you essentially just follow the same guidelines from C#, i.e. you create your custom middleware class and then add an extension method, that adds the middleware to the pipeline.
so for you, try this:

````F#
open Microsoft.AspNetCore.Http
open Giraffe
open Microsoft.Net.Http.Headers

// F# class for your custom middleware
type CustomCacheMiddleWare (next: RequestDelegate) =
    
    do if isNull next then raise (ArgumentNullException("next"))

    member __.Invoke (ctx: HttpContext) =
        task {
            let cacheControl = CacheControlHeaderValue()
            cacheControl.Public <- true
            cacheControl.MaxAge <- new Nullable<TimeSpan>(TimeSpan.FromSeconds(60.))
            ctx.Response.GetTypedHeaders().CacheControl <- cacheControl
            return next.Invoke ctx
        }

// Extension method that adds your custom middleware to pipeline
type IApplicationBuilder with

    member this.UseCustomCache() = this.UseMiddleware<CustomCacheMiddleWare>()

// Configure and add your middleware with the extension method
let configure (app : IApplicationBuilder) =
    //... others
    app.UseCustomCache() |> ignore
````

**Comment by BrianVallelunga** [comment]
Thanks @ebi-igweze. That worked for me.

It does seem like a Giraffe-specific version of the attribute would be useful to aid in composition. I may investigate how that might be made, but I'm pretty new to Giraffe.

**Comment by toburger** [comment]
This giraffe handler should work:

```fsharp
let withResponseCaching seconds (handler: HttpHandler): HttpHandler =
    fun next ctx -> task {
        ctx.Response.GetTypedHeaders().CacheControl <-
            CacheControlHeaderValue(
                Public = true,
                MaxAge = Nullable (TimeSpan.FromSeconds (float seconds))
            )
        ctx.Response.Headers.[HeaderNames.Vary] <- StringValues [| "Accept-Encoding" |]
        return! handler next ctx
    }
```

Usage:

```fsharp
withResponseCaching 100 mywebpartorroutetocache
```

Do not forget to register the response caching middleware with `app.UseResponseCaching()` and `services.AddResponseCaching()`

**Comment by BrianVallelunga** [comment]
Thanks!
