### ISSUE TITLE
How to register singleton service that requires access to IConfiguration?

### ISSUE THREAD

**Issue by BrianVallelunga** [giraffe-fsharp/Giraffe#240]
I'm using the 1.1 version of Giraffe and building off of the standard template project. My code looks like:

    let configureServices (services : IServiceCollection) =
        services.AddCors()    |> ignore
        services.AddGiraffe() |> ignore

    let configureAppConfiguration (context: WebHostBuilderContext) (config: IConfigurationBuilder) =
        config
            .AddJsonFile("appsettings.json", false, true)
            .AddEnvironmentVariables() |> ignore

    // In main:
    let contentRoot = Directory.GetCurrentDirectory()
    let webRoot     = Path.Combine(contentRoot, "WebRoot")
    WebHostBuilder()
        .UseKestrel()
        .UseContentRoot(contentRoot)
        .UseIISIntegration()
        .UseWebRoot(webRoot)
        .ConfigureServices(configureServices)
        .ConfigureAppConfiguration(configureAppConfiguration)
        .Configure(Action<IApplicationBuilder> configureApp)
        .ConfigureLogging(configureLogging)
        .Build()
        .Run()

How would I register a new singleton in my `configureServices` function using `services.AddSingleton` if I needed access to the `IConfiguration` object to construct my singleton service? The ordering seems to be all wrong here. Even if I switch the order of `ConfigureAppConfiguration` and `ConfigureServices`, there doesn't seem to be a way to pass the configuration object between the two functions. I know how to do this with a Startup class, but is there a recommended functional way with Giraffe?

Thank you.

**Comment by dustinmoris** [comment]
ASP.NET Core let's you build a service provider during service registration as this is a common use case for many applications:

```fsharp
let configureServices (services : IServiceCollection) =
    let sp = services.BuildServiceProvider()
    let config = sp.GetService<IConfiguration ()
    ...
```

**Comment by BrianVallelunga** [comment]
Thanks. That should work.
