### ISSUE TITLE
Parse query string comma-separated values as list

### ISSUE THREAD

**Issue by cmeeren** [giraffe-fsharp/Giraffe#243]
I'd like to deserialize the query string `?flags=favorite,hidden` to the type `Query` as defined below:

```f#
type Flag = Favorite | Hidden
type Query = {Flags: Flag list}
```

Is this possible using Giraffe? I've only managed to use lists in query strings by repeating the parameter:  `?flags=favorite&flags=hidden`.

(Please disregard the actual DU related stuff; I've fixed that by using FSharpLu.Json.)

**Comment by dustinmoris** [comment]
Hi @cmeeren, the way list items are passed through a query string is by specifying the parameter multiple times like in your second example. See https://github.com/giraffe-fsharp/Giraffe/issues/121#issuecomment-364953107

In this case ASP.NET Core has already decomposed the query string into a list and Giraffe is simply serializing the string values into the correct type.

You client application basically has to send list items in the correct format is the answer I am afraid.

**Comment by cmeeren** [comment]
Thanks for the tip. I too was under the impression that specifying the parameter multiple times was the correct way, but our front-end developer suggested using comma-separated values, so I just wanted to check if this was something Giraffe supported. It seems we should indeed stick to the standard way of doing things.

**Comment by cmeeren** [comment]
On the other hand, the [JSON API spec](http://jsonapi.org/format/#fetching-includes) specifies that comma-separated values is mandatory behavior (link to first mention). Do you think it would be possible and desirable for Giraffe to add support for this?

**Comment by narve** [comment]
> 
> 
> On the other hand, the [JSON API spec](http://jsonapi.org/format/#fetching-includes) specifies that comma-separated values is mandatory behavior (link to first mention). Do you think it would be possible and desirable for Giraffe to add support for this?

Good point - although I don't like JSON APIs specification, it should be easy to follow it. 
Has this been resolved, or an easier workaround found?

**Comment by cmeeren** [comment]
I am splitting manually.

As a side note, I am also using [FSharp.JsonApi](https://github.com/cmeeren/FSharp.JsonApi/), which makes JSON:API much more pleasant to use with F#. It has (among many other things) built-in helpers for parsing comma-separated query strings.

**Comment by narve** [comment]
All right, thanks for the info!
