### ISSUE TITLE
How would I plug OpenIddict into Giraffe?

### ISSUE THREAD

**Issue by xperiandri** [giraffe-fsharp/Giraffe#245]
Or maybe it is required another Giraffe optimized middleware on top of [OpenIdConnectServer](https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server)?

[OpenIddict](https://github.com/openiddict/openiddict-core/)

**Comment by xperiandri** [comment]
@distinmoris, @Krzysztof-Cieslak
Do you have any consideration about the topic?

**Comment by xperiandri** [comment]
OpenID Connect authentication in particular

**Comment by dustinmoris** [comment]
Hi, Giraffe should work with OpenIdConnectServer without any issues. What problems were you facing when plugging OpenIdConnect into ASP.NET Core in combination with Giraffe? Have you got a repository which I can have a look at?

**Comment by xperiandri** [comment]
Ah, I've got it from samples.
It is enough to set up OpenIddict as ASP.NET Core middleware before Giraffe middleware.
