### ISSUE TITLE
routefx?

### ISSUE THREAD

**Issue by cmeeren** [giraffe-fsharp/Giraffe#246]
I am routing using `routef "/orders/%s" (fun orderNumber -> ...)`, but I would like to also match routes with a trailing slash, which seems to be the domain of `routex`. However, I can't find a handler that combines `routef` and `routex`. Is there one? Is there another way to accomplish this?

**Comment by dustinmoris** [comment]
Hi, you are right there is currently no `routefx`. I think it should be possible to implement one and I'd accept a PR for it if you want to work on it.

**Comment by cmeeren** [comment]
Thanks. Totally swamped for the time being, so I'll have to leave it for someone else.

**Comment by JamesFaix** [comment]
@dustinmoris I would like to contribute, but I am not sure I understand the desired behavior.  Is this a function that should match a regex path, and then pull variables out of regex captures? 

For example, would you use a string like `"""orders/(\d+)/?"""` to match any of these routes:
`orders/123`
`orders/123/`
and then pass `123` into the handler?

**Comment by cmeeren** [comment]
My desired behavior is that

`routefx "/orders/%s/?" (fun orderNumber -> ...)`

should match

`/orders/123`
`/orders/123/`

In order words, exactly the same as

`routef "/orders/%s" (fun orderNumber -> routex "/?" >=> ...)`

**Comment by cmeeren** [comment]
Note that this isn't terribly important to me, because often, I have multiple endpoints for each `routef` and must use the latter approach anyway using `subRoutef` (the below is from the top of my head, there might be mistakes):

```f#
subRoutef "/orders/%s" (fun orderNumber ->
  choose [
    routex "/?" >=> GET_HEAD >=> getOrder
    routex "/?" >=> DELETE >=> deleteOrder
    routex "/purchase/?" >=> POST >=> purchaseOrder
  ]
)
```

**Comment by JamesFaix** [comment]
What I don't understand is how a function would be written that interprets part of a string as a regex and part of it as a `PrintfFormat`. Is this something that should only handle the specific case of an optional trailing `/`, or any combination of regex and format string?

**Comment by cmeeren** [comment]
I haven't thought through whether it's simple or even possible to implement this. Personally I'd be happy if it was just agnostic regarding the trailing slash.

**Comment by dustinmoris** [comment]
Please have a look if `routexp` which was discussed in #446 works for you.

**Comment by dustinmoris** [comment]
Closing for now as I think `routexp` solves this issue, but please re-open if I got it wrong.
