### ISSUE TITLE
Inline SVG

### ISSUE THREAD

**Issue by nagpal** [giraffe-fsharp/Giraffe#247]
Hi, 

Is there any support in the giraffe View Engine for cases where we have inline svgs?

-Vijay

**Comment by dustinmoris** [comment]
Yes, have a look at https://github.com/dustinmoris/CI-BuildStats, particularly have a look at https://github.com/dustinmoris/CI-BuildStats/blob/master/src/BuildStats/Views.fs#L20 and https://github.com/dustinmoris/CI-BuildStats/blob/master/src/BuildStats/Program.fs#L28 where I use the Giraffe view engine to render SVG images. You can just output that SVG tag inside a HTML page as well.

**Comment by nagpal** [comment]
Thanks a lot!
