### ISSUE TITLE
Just following the readme instructions doesn't get me a working Giraffe app

### ISSUE THREAD

**Issue by halcwb** [giraffe-fsharp/Giraffe#248]
When I just follow the readme instructions by:

- Creating a new console application
- Adding and installing Giraffe using Paket
- Creating the basic Program

I get an error WebHostBuilder not defined.

When I add the following (I don't need all I think) resolves the issue

Microsoft.AspNetCore.Cors
Microsoft.AspNetCore.Hosting
Microsoft.AspNetCore.Diagnostics
Microsoft.AspNetCore.Server.Kestrel
Microsoft.AspNetCore.Server.IISIntegration
Microsoft.Extensions.Logging.Console
Microsoft.Extensions.Logging.Debug
Microsoft.Extensions.DependencyInjection
Giraffe

And this is what you need to open for the minimal app:

```
    open System
    open Microsoft.AspNetCore.Builder
    open Microsoft.AspNetCore.Hosting
    open Microsoft.Extensions.DependencyInjection
    open Giraffe

```

**Comment by dustinmoris** [comment]
Hi @halcwb,

Can you point me to the place in the README where you think I've missed adding some information?

Or feel free to send me a PR with the proposed changes to the README!

Thanks for the help, much appreciated!

**Comment by kaspermoerch** [comment]
I have experienced the same issue - WebHostBuilder can not be resolved, when following the "

I added Giraffe to my project with:
`dotnet add [PROJECT] package Giraffe --package-directory [PACKAGE_CIRECTORY]`

The code does not compile.

After adding the package Microsoft.AspNetCore the code compiles:
`dotnet add [PROJECT] package Microsoft.AspNetCore --package-directory [PACKAGE_CIRECTORY]`

**Comment by dustinmoris** [comment]
Ok I see.. you followed the manual steps. I will update the open statements in the example there. Thanks for letting me know!

**Comment by dustinmoris** [comment]
Updated the README based on the feedback here. Thanks again!
