### ISSUE TITLE
GiraffeViewEngine - button onclick event is missing

### ISSUE THREAD

**Issue by TheDevKnight** [giraffe-fsharp/Giraffe#255]
Hi,

is the onclick event on the button really not available?

button [ _onclick ??? ] [ ]

As a workaround i could add the event in my javascript. Is this the correct way?

Thanks for help.

Regards

**Comment by dustinmoris** [comment]
Hi, if the _onclick event is missing then you can [create it yoursef](https://github.com/giraffe-fsharp/Giraffe/blob/master/DOCUMENTATION.md#custom-elements-and-attributes) or submit a PR!

**Comment by TheDevKnight** [comment]
@dustinmoris Thank you! Works perfect and very easy :)

**Comment by dustinmoris** [comment]
This has been released with [Giraffe 2.0.0](https://github.com/giraffe-fsharp/Giraffe/releases/tag/v2.0.0).
