### ISSUE TITLE
Html form automatically submits

### ISSUE THREAD

**Issue by matthewblott** [giraffe-fsharp/Giraffe#259]
The first time the application runs the login form (which exists in a partial view) is submitted. I was a bit confused as I kept seeing the url change to 'login-failed' but noticed the ```loginHandler``` function was being called. As soon as I removed the form element the handler wasn't called. This only happens when the application starts and subsequent requests work as expected. The HTML is pretty basic, I can see no reason why this would get called. I have tried it in different browsers and the result is the same.

```
<form method="post" action="/login">
  <input name="name" placeholder="name">
  <input name="password" placeholder="password" type="password">
  <button>login</button>
</form>

```

**Comment by matthewblott** [comment]
Oops, seems it is a chrome issue. Closing (sorry).

**Comment by ImaginaryDevelopment** [comment]
what was the chrome issue? can you give more details? may have something similar happening to me.
