### ISSUE TITLE
build.sh is non-executable and has windows eol on linux.

### ISSUE THREAD

**Issue by sashang** [giraffe-fsharp/Giraffe#260]
When using linux and installing the template build.sh is installed non-executable and has Windows CRLF newline symbols. Recommend changing this so that it is installed with executable bit set and with Unix newlines.

**Comment by dustinmoris** [comment]
Ok thanks, will look into it. I don't have a Unix environment currently at hand so would appreciate some help with it if it is urgent. I normally develop from macOS (not right now though) and the build.sh worked fine there, which is why I probably haven't noticed this yet.

**Comment by TheAngryByrd** [comment]
The giraffe template? Yeah looks like we need to add https://github.com/TheAngryByrd/MiniScaffold/blob/master/Content/.template.config/template.json#L19-L28 to it.

**Comment by sashang** [comment]
I can look into this . I don't have a Mac so I can't corroborate this. Odd that it worked on the Mac.

**Comment by TheAngryByrd** [comment]
It's a problem with dotnet's templating engine unfortunately.  We should probably move this to the giraffe-template repo.

**Comment by dustinmoris** [comment]
This has been fixed in the last Giraffe and giraffe-template releases. Thanks for helping out!
