### ISSUE TITLE
Microsoft Active Directory & Giraffe

### ISSUE THREAD

**Issue by wiredsister** [giraffe-fsharp/Giraffe#263]
Hi Giraffe amigos, 

In your examples directory, I've gotten far with the JWT tokens example (which partially meets my needs), but I'm looking for a more comprehensive example of checking claims in Azure Graph API. I see in `Properties/launchSettings.json` there is this configuration: 
```
    "windowsAuthentication": false,
    "anonymousAuthentication": true,
```
I presume it's more complicated than flipping a boolean flag. Is there a need for someone to contribute back such an example and/or creating a Giraffe extension to AD as a middleware? If not, can someone point me to a relevant example? I looked on https://github.com/thangchung/awesome-dotnet-core#sample-projects but only found https://github.com/Azure-Samples/guidance-identity-management-for-multitenant-apps.

Thanks,
Gina

**Comment by lukethenuke** [comment]
I'm not sure exactly what you are asking, but should use `AddOpenIdConnect` instead of the JWT bearer since Azure AD is an OpenId Connect compatible IDP.  
Then you could either configure AAD to [return your custom claims](https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-optional-claims) or hook into the `OnUserInformationReceived` event simply do an Graph API request for each auth.

**Comment by WalternativE** [comment]
> Also, what is an IDP?

I think the abbreviation stands for identity provider if I'm not totally mistaken.

To examples - currently doing some research for work and regarding integration to everything based on ASP.NET core [this](https://github.com/Azure-Samples/active-directory-dotnet-webapp-openidconnect-aspnetcore) example as well as [this](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/azure-ad-b2c-webapi?view=aspnetcore-2.1) docs page seem to be the most promising. The magic appears to happen mostly in the setup.

I'm not entirely sure about the additional configurations in Giraffe but I think something in the direction of the `Saturn` [JWT implementation](https://github.com/SaturnFramework/Saturn/blob/master/sample/JWTSample/JWTSample.fs) could be a step into the right direction.

If you get it to work - would you be so kind and share your experiences?

**Comment by lukethenuke** [comment]
> I'm asking how can I have my Giraffe endpoints authorized using Azure Active Directory.

I don't think there is anything Giraffe specific problem when using AAD. If you set up the `AddOpenIdConnect` middleware correctly you can get the ClaimPrincipal from the HttpContext.User property which should contain the data from AAD. How you want to enforce it on each Giraffe endpoint is up to you, but you could do something similar to the `mustBeAdmin` and `mustBeJohn` functions in the sample app.

>Can you be more specific and link me to the nuget package or project you're referring to for AddOpenIdConnect? I found this inside this package. And hopefully rc2 means a stable version?

Nope, that is the server, you should use the client middleware [Microsoft.AspNetCore.Authentication.OpenIdConnect](https://www.nuget.org/packages/Microsoft.AspNetCore.Authentication.OpenIdConnect/)

>Also, what is an IDP?

Identity Provider, fancy OpenId Connect name for "webserver that do logins" (in this case, azure ad)

> Code

Here is a complete example, note that you may need to change some settings to match your own configuration.

```fsharp
open System
open Microsoft.AspNetCore.Http
open Microsoft.AspNetCore.Builder
open Microsoft.AspNetCore.Hosting
open Microsoft.Extensions.DependencyInjection
open Microsoft.AspNetCore.Authentication.OpenIdConnect
open Microsoft.AspNetCore.Authentication.Cookies
open Giraffe

let redirectUri = "http://localhost:5000/"
let clientId = "dd5c044f-c2cd-4e8d-b39b-830c02ea911a"
let tenantId = "dd5c044f-c2cd-4e8d-b39b-830c02ea911b"

let view = fun (next : HttpFunc) (ctx : HttpContext) ->
    let name = ctx.User.FindFirst("name").Value
    text name next ctx

let mustBeAuthed = requiresAuthentication <| challenge OpenIdConnectDefaults.AuthenticationScheme 

let webApp = mustBeAuthed >=> view

let configureApp (app : IApplicationBuilder) = 
    app
        .UseAuthentication()
        .UseGiraffe(webApp)

let configureServices (services : IServiceCollection) =
    services.AddAuthentication(fun o ->
            o.DefaultScheme <- CookieAuthenticationDefaults.AuthenticationScheme
        )
        .AddOpenIdConnect(fun o ->
            o.Authority <- "https://login.microsoftonline.com/" + tenantId
            o.ClientId <- clientId
            o.ResponseType <- "id_token"
            
            // You can do some mapping with this if there is extra claims to map
            // o.ClaimActions

            // or even this event to do more custom stuff
            // o.Events.OnUserInformationReceived <- fun u -> 
            //     let i = u.Principal.Identity :?>  System.Security.Claims.ClaimsIdentity
            //     i.AddClaim(System.Security.Claims.Claim("test-claim", "value"))
                
            //     System.Threading.Tasks.Task.CompletedTask
        )
        .AddCookie()
    |> ignore

    services.AddGiraffe() 
    |> ignore

[<EntryPoint>]
let main _ =
    WebHostBuilder()
        .UseKestrel()
        .Configure(Action<IApplicationBuilder> configureApp)
        .ConfigureServices(configureServices)
        .Build()
        .Run()
    0
```

**Comment by dustinmoris** [comment]
Sorry closed this issue a bit late, but it was essentially resolved for a while now.
