### ISSUE TITLE
Combine routef with model binding HttpHandler

### ISSUE THREAD

**Issue by scorelocity** [giraffe-fsharp/Giraffe#266]
Is it possible to combine the handling of a route with parameters using routef with a model binding HttpHandler function so that the route parameter and bound model get passed to the same function? Something like:

```
choose [
  POST
    >=> routef "/%s" (fun id -> someFunction id)
    >=> bindForm<Car> (Some british) (fun car -> myFunction id car) // want to pass id from routef and car into same function. 
]
```

**Comment by dustinmoris** [comment]
Hi,

Sorry for the super late reply, but you can combine them like this for example:

```fsharp
let combinedHandler (name : string) (age : int) : HttpHandler =
    fun (next : HttpFunc) (ctx : HttpContext) ->
        task {
            let! car = ctx.BindJsonAsync<Car>()

            return! ctx.WriteTextAsync(sprintf "%s %s %s" name age car.Model)
        }
```

Hope this is still helpful, let me know if you have more questions!

**Comment by scorelocity** [comment]
Thanks!
