### ISSUE TITLE
"Doing it manually" section of Readme could use additional information

### ISSUE THREAD

**Issue by NatElkins** [giraffe-fsharp/Giraffe#270]
When trying the "Doing it manually" example, it took a little while to figure out which packages needed to be referenced in order for the example to work.  In addition to Giraffe, the Microsoft.AspNetCore.Hosting and Microsoft.AspNetCore.Server.Kestrel packages need to be referenced.  Would an update to the Readme be a welcome PR?

**Comment by dustinmoris** [comment]
Yes any improvements to user documentation are always welcome! Especially now with .NET Core 2.1 and the `Microsoft.AspNetCore.App` and `Microsoft.AspNetCore.All` shared runtime packages it should be fairly easy.

**Comment by dustinmoris** [comment]
Updated the README based on the feedback here. Thanks again!
