### ISSUE TITLE
Can't get the warbler to work

### ISSUE THREAD

**Issue by seankearon** [giraffe-fsharp/Giraffe#271]
So that my function will be evaluated each time it's called, I'm trying to use the `warbler` from the [docs](https://github.com/giraffe-fsharp/Giraffe/blob/master/DOCUMENTATION.md#warbler).

However, when I call `/warbler` I get the same result each time.  This is how I set it up:

`dotnet new -i "giraffe-template::*"` (Installs 0.17.0)
`dotnet new giraffe -lang=f#`

Here's the code:

```
let warbler f a = f a a

let time() = System.DateTime.Now.ToString()

let webApp =
    choose [
        GET >=>
            choose [
                route "/" >=> indexHandler "world"
                routef "/hello/%s" indexHandler

                route "/normal"  >=> text (time())
                route "/warbler" >=> warbler (fun _ -> text (time()))
            ]
        setStatusCode 404 >=> text "Not Found" ]
```
Then `dotnet run` and going to `/warbler` and refreshing a few times shows the same time for each call.  I was expecting the time to be updated on each call.  

Am I missing something?

**Comment by bsloanincomm** [comment]
That warbler function as defined in the documentation definitely does achieve the desired result. You can just use the warbler function that is defined globally by Giraffe and that should work (just delete your definition of warbler). The documentation could use an update to remove that ```let warbler f a = f a a``` definition.

**Comment by seankearon** [comment]
Thanks @bsloanincomm - that works perfectly!
