### ISSUE TITLE
Getting Error NU1108   Cycle detected

### ISSUE THREAD

**Issue by wterreb** [giraffe-fsharp/Giraffe#274]
Just trying out Giraffe HelloWorld  example, but get an error that reads:
```
Error    NU1108    Cycle detected.
Giraffe -> Giraffe (>= 1.1.0).
```
(using dotnet core version 2.1.300)

Same thing also happens when I try to run build.bat:
```
c:\Work\PC\Test>build.bat
c:\Work\PC\Test>dotnet restore src/Giraffe 
  Restoring packages for c:\Work\PC\Test\src\Giraffe\Giraffe.fsproj...
c:\Work\PC\Test\src\Giraffe\Giraffe.fsproj : error NU1108: Cycle detected.
c:\Work\PC\Test\src\Giraffe\Giraffe.fsproj : error NU1108:   Giraffe -> Giraffe (>= 1.1.0).
```

Tried renaming the folder etc, but could not get past this problem yet.

**Comment by nozzlegear** [comment]
I'm also getting this when using the `dotnet new giraffe` template and then running `build.bat`.

**Comment by nozzlegear** [comment]
My project was named "giraffe". I renamed it to something else and tried again, this time it worked! It looks like dotnet restore is getting confused by both the project and the package being named Giraffe.

**Comment by forki** [comment]
Yes that's a known dotnet cli issue.

Joshua Harms <notifications@github.com> schrieb am Di., 5. Juni 2018, 22:49:

**Comment by dustinmoris** [comment]
Thanks for reporting this. I will document it in the template project, where I have created an issue for it now.
