### ISSUE TITLE
Adding Giraffe to Tech empower benchmark suite

### ISSUE THREAD

**Issue by rishavs** [giraffe-fsharp/Giraffe#277]
Currently there are no fsharp frameworks in the TE benchmarks while multiple c# frameworks are in contention. With the use of Kestrel, Giraffe may prove to be a strong competitor. It will also bring in greater recognition and increase the project's visibility.

https://www.techempower.com/benchmarks/#section=data-r16&hw=ph&test=fortune

**Comment by rishavs** [comment]
https://github.com/TechEmpower/FrameworkBenchmarks/pull/3859

Its already underway. This issue is not needed.

**Comment by forki** [comment]
Please reopen. We should discuss how to improve it

Rishav Sharan <notifications@github.com> schrieb am Mi., 20. Juni 2018,
19:30:

**Comment by dustinmoris** [comment]
Hi,

We just closed a PR which improves the perf of the `GriaffeViewEngine` and there is another issue open to improve JSON serialization. I think this will be an ever ongoing issue and something which we will have to reiterate over and over again.

I'd be inclined to close this issue and just tackle the concrete perf improvement issues which anyone can open.

If anyone knows of good ways to improve giraffe's perf in those benchmarks without completely breaking its programming model then feel free to open a ticket :).
