### ISSUE TITLE
The browser is openend despite is not runing the server?

### ISSUE THREAD

**Issue by mamcx** [giraffe-fsharp/Giraffe#278]
I have a test suite that exercise several aspects of the API.  However, the browser is always opened automatically and I haven't put the server to listen. I only import giraffe as part of the dependencies.

Neither I see where to look to know what is requesting this.

**Comment by dustinmoris** [comment]
Hi, would you mind sharing some of the code or steps to reproduce? I am not 100% sure I know what you mean. Is it that your browser opens a new window when you execute `dotnet run`?

**Comment by mamcx** [comment]
I run `dotnet run` and keep the server in the terminal. Then if I run any project in Visual Studio Mac that reference the server (like the tests) it open the browser. I don't do a HTTP call anywhere, this just happened..

**Comment by dustinmoris** [comment]
Ok, I am afraid I can't really help with this. Giraffe is most certainly not opening any browser windows and to me this sounds more of a Visual Studio behaviour. I would suggest to [report a problem for Visual Studio for Mac](https://docs.microsoft.com/en-gb/visualstudio/mac/report-a-problem).

**Comment by mamcx** [comment]
I also use Suave (because giraffe trigger a weird bug in android) and this not happened with it, neither with other web frameworks I have tested. Is sure in the giraffe codebase not launch  browser windows?

**Comment by forki** [comment]
I'm very positive that giraffe does not open a browser. Maybe you are using
a FAKE script that does it? Or canopy?

Mario Montoya <notifications@github.com> schrieb am Do., 16. Aug. 2018,
16:50:

**Comment by dustinmoris** [comment]
I'm going to close this too as there hasn't been any more information provided for a month now. If you still struggle with this @mamcx then please open a new issue and give us a bit more context in order to help you!
