### ISSUE TITLE
Html view rendering performance

### ISSUE THREAD

**Issue by dv00d00** [giraffe-fsharp/Giraffe#281]
I've added a stripped implementation of html view rendering to the techempower tests repo. It finished test run today. These are results https://www.techempower.com/benchmarks/#section=test&runid=3da523ee-fff1-45d8-9044-7feb532bf9ee&hw=ph&test=fortune&w=zik0zj-hr4e7z&a=2

| name | rps |
|-------------------|---------|
|  giraffe-stripped | 174,979 | 
|  giraffe          | 41,136  |  

While testing stripped version I observed that to render fortunes html the html generation itself produces around 100 KB allocation.

What I did is very straightforward, I just rendered html to the memory stream instead of relying on string concatenation as in current implementation, it surely can be optimized more. @gerardtoconnor has investigated this area deeply. Please take a look at this https://github.com/gerardtoconnor/ViewEngineTests/blob/master/TemplateViewEngine.fs

Fortunes tests were added in this PR https://github.com/TechEmpower/FrameworkBenchmarks/pull/3863

**Comment by gerardtoconnor** [comment]
Great work @dv00d00 !! I think your solution it great, in line with my [ByteViewEngine ](https://github.com/gerardtoconnor/ViewEngineTests/blob/master/ByteViewsAsync.fs) & already very high up there in the rankings.

I'm looking into how we can juice more performance out of the framework, once that is done I can look into the templating a bit more but I think you're 90% there.

**Comment by dustinmoris** [comment]
First of all congrats on these great results! Secondly I would love to get your changes from string concatenation to memory stream put into the current GiraffeViewEngine. A PR is more than welcome! Let me know if this is something you would like to work on or if it is up for grabs for somebody else!

Thanks a lot!

**Comment by dustinmoris** [comment]
Release is out: https://github.com/giraffe-fsharp/Giraffe/releases/tag/v3.0.0

Thanks for the great contributions! :) 👍
