### ISSUE TITLE
HttpContext.BindModelAsync doesn't work for HTTP DELETE method.

### ISSUE THREAD

**Issue by chyczewski-maciej** [giraffe-fsharp/Giraffe#287]
According to Mozilla HTTP DELETE method may contain body.
https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/DELETE

According to HTTP ** Hypertext Transfer Protocol (HTTP/1.1): Semantics and Content** document:
>    A payload within a DELETE request message has no defined semantics;
   sending a payload body on a DELETE request might cause some existing
   implementations to reject the request.
https://tools.ietf.org/html/rfc7231#page-30

**Comment by chyczewski-maciej** [comment]
If nobody will disagree I will create a PR to support it

**Comment by TheAngryByrd** [comment]
Fixed in #288
