### ISSUE TITLE
Authorize with a specific scheme

### ISSUE THREAD

**Issue by nikoudel** [giraffe-fsharp/Giraffe#289]
Hi,

I'm trying to setup scenario described [here](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/limitingidentitybyscheme?view=aspnetcore-2.1&tabs=aspnetcore2x), namely use cookie-based authentication to log in and JWT bearer authentication for JavaScript requests.

The problem is neither the Authorize attribute nor the service-configured controller policies are available anymore. Any clues how to do it with Giraffe?

**Comment by danieljsummers** [comment]
#224 may be of some interest to you.

**Comment by danieljsummers** [comment]
I've now done a piece of this (the JWTs) in another app. It looks like you [set up authentication as part of the services configuration](https://github.com/bit-badger/myPrayerJournal/blob/2bf3bc4865818de3f335cbb699ce254ca2c68c1f/src/api/MyPrayerJournal.Api/Program.fs#L38), then ["use" it in the application configuration](https://github.com/bit-badger/myPrayerJournal/blob/2bf3bc4865818de3f335cbb699ce254ca2c68c1f/src/api/MyPrayerJournal.Api/Program.fs#L87).

Once you've done that, the runtime populates the `User` property on the `HttpContext` you'll receive in your handlers. I created a [function to try to extract the user's identifier claim](https://github.com/bit-badger/myPrayerJournal/blob/2bf3bc4865818de3f335cbb699ce254ca2c68c1f/src/api/MyPrayerJournal.Api/Handlers.fs#L42), and then [handler that authorizes based on whether that returns `Some` or `None`](https://github.com/bit-badger/myPrayerJournal/blob/2bf3bc4865818de3f335cbb699ce254ca2c68c1f/src/api/MyPrayerJournal.Api/Handlers.fs#L63). In each handler that requires it, [I add it with the fish operator to my actual handler function](https://github.com/bit-badger/myPrayerJournal/blob/2bf3bc4865818de3f335cbb699ce254ca2c68c1f/src/api/MyPrayerJournal.Api/Handlers.fs#L109). (I'm using the token router, so I can't include it in the tree; if you're using the standard router, you could include it there as well.)

At any rate, I believe you could probably use this pattern, one for cookies and one for JWTs, but I'm almost thinking that if you configure both, it may "just work" (things like `Request.IsAuthenticated()`, the `User` property, etc.). At one point, I had gone down the rabbit hole of extracting the Authorization service from DI, trying to create a policy, etc., but all I really needed was that user ID. :) If it's there, you're good; if not, you're not. (This app intentionally store as little about the user as possible; there's not even a "user" table!)

**Comment by dustinmoris** [comment]
This has been released with [Giraffe 2.0.0](https://github.com/giraffe-fsharp/Giraffe/releases/tag/v2.0.0).
