### ISSUE TITLE
[Proposal] Add encoding to content type response headers

### ISSUE THREAD

**Issue by dv00d00** [giraffe-fsharp/Giraffe#311]
The source of this stuff is the techempower benchmark.

They require `text\html; charset=utf-8` content type header to be present.

It does affect browser behavior for nonascii html. I think we should include it by default for html and add a way to disable it somehow.

Other than that charset would be useful for all other response writers.

**Comment by dv00d00** [comment]
before 
![image](https://user-images.githubusercontent.com/1162823/46318103-09a4b180-c5de-11e8-860a-4f9e2abe801a.png)

after
![image](https://user-images.githubusercontent.com/1162823/46318129-1f19db80-c5de-11e8-859e-31beba19775b.png)

**Comment by dv00d00** [comment]
Actually I am not sure it should be optional

**Comment by dv00d00** [comment]
Anyway, opened a pr #312 with the assumption that we wont need to omit charset in content type

**Comment by dustinmoris** [comment]
This change is included in v.3.2.0, which is currently being cooked on the build server and then pushed to NuGet.
