### ISSUE TITLE
Identity with JWT not working

### ISSUE THREAD

**Issue by oleksandrmelnychenko** [giraffe-fsharp/Giraffe#313]
Both services are not working ?  

**services.AddAuthentication**(JwtBearerDefaults.AuthenticationScheme).AddJwtBearer(Action<JwtBearerO
          ptions>jwtBearerOptions) |> ignore
      
**services.AddIdentity**<User, IdentityRole>(fun options -> 
                options.Password.RequireUppercase <- false 
                options.Password.RequiredLength <- 4
                options.Password.RequireDigit <- false
                options.Password.RequiredUniqueChars <- 0
                options.Password.RequireLowercase <- false
                options.Password.RequireNonAlphanumeric <- false
            ).AddEntityFrameworkStores<DriveIdentityContext>() |> ignore

**Comment by oleksandrmelnychenko** [comment]
Hi, 
If I include both: AspNet Identity and JwtBearer into "configureServices", Jwt logic not working (always return 401, AspNet Identity configuration has '<more priority>'. In default Asp.Net core, no such issue, i can use jwt with asp.netIdentity

**Comment by oleksandrmelnychenko** [comment]
Middleware for Token validation not working properly if AspNet identity was added to Services

**Comment by dustinmoris** [comment]
Hi, were you able to fix your issue? Sounds like you had two middlewares clashing with each other?
