### ISSUE TITLE
"rawText"

### ISSUE THREAD

**Issue by AkosLukacs** [giraffe-fsharp/Giraffe#315]
Hi!

Although the documentation clearly states that `rawText` is dangerous, and `encodedText` should be used in most cases, I think it could be more apparent:

- Add relevant comments in GiraffeViewEngine
- Remove most of `rawText` from the samples. Looks like `rawText` is used to output static text, and that is safe, but I think the samples could be safer by default. Copy-paste anyone? :)
- `comment` also does not encode it's content. I think it's really and edge case, but maybe that should use encoding by default as well?
- Possibly a shorter alias for `encodedText` (it's longer to type than `rawText`). Razor's `@` is pretty good in this sense: it's short, and it's safe by default. Something similar might be good. Or `str` from Fable / React was mentioned somewhere.

Started working on the first two, since those are "just" docs.

**Comment by dustinmoris** [comment]
Hi,

Thanks for raising all these points and providing the PR (which I have already happily merged)!

> comment also does not encode it's content. I think it's really and edge case, but maybe that should use encoding by default as well?

This is an interesting one. I am not sure about this, because with a comment I am not sure if encoding would be really desired. For example someone might have a comment like this:

```
<!-- Consider using <pre><code></code></pre> instead: -->
<pre>Some code</pre>
```

Not sure, what do you think would be the risks by not encoding?

> Possibly a shorter alias for encodedText (it's longer to type than rawText). Razor's @ is pretty good in this sense: it's short, and it's safe by default. Something similar might be good. Or str from Fable / React was mentioned somewhere.

I can see the appeal of a short alias. What would be your personal preference here?

**Comment by AkosLukacs** [comment]
Hi, glad to help!

On comment, I might have gone too far, might not make sense.

For the short alias: `@` is already used in F#, and probably a lot of operators I don't even know about. @nojaf mentioned `str` in #138 and that feels good to me for the same reason: I personally used Fable / React before using Giraffe's view engine. But this should be a community decision.

**Comment by nojaf** [comment]
Not that this helps anyone but I use the FableReact as view engine these days. Serverside all you need is `Fable.Helpers.ReactServer.renderToString` and you can re-use the same rendering as you know on the clientside. You don't necessarily need to do the isomorphic dans, works well enough.

**Comment by dustinmoris** [comment]
@nojaf Thanks for the tip!
@AkosLukacs I've added the `str` alias. I think that solves everything you've mentioned here now right?

**Comment by AkosLukacs** [comment]
@dustinmoris Yes, thank you!

@nojaf Thanks for the info, haven't looked into SSR, and it's good to know that you can simply render FableReact 👍
