### ISSUE TITLE
Access Giraffe sample on Service Fabric cluster on Azure

### ISSUE THREAD

**Issue by FedericoBinda** [giraffe-fsharp/Giraffe#318]
Hi

I am trying to have a Giraffe application running on a Service Fabric cluster on Azure.
So far I have managed to deploy the Giraffe sample to the cluster as a guest executable, and when I connect to the cluster via Remote Desktop I can see it is running at http://localhost:5000 as expected. However I am not able to connect to it remotely. I think I have set up things correctly on the cluster, even though I am not 100% sure. Therefore my question is: is there some modification that I need to apply to the sample in order to make it accessible remotely?

**Comment by havarnov** [comment]
I think your problem is that you need to configure the load balancer in front of your cluster. See https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-reverseproxy

**Comment by dustinmoris** [comment]
@FedericoBinda How are you getting on with this?

**Comment by FedericoBinda** [comment]
Not well unfortunately. I tried the basic ASP.NET core hello world application, but I ran into the same issue. I must be doing something wrong in the Service Fabric network configuration, but I am having a hard time figuring out what.
I think it's clear now that this is a service fabric related issue. I have opened an issue [here](https://github.com/Microsoft/service-fabric/issues/252) but unfortunately no answer yet.

**Comment by FedericoBinda** [comment]
I solved the issue. It turns out that it is necessary to set the correct url in the app to be able to access it remotely. At the moment I am using a hard-coded url in the code with UseUrls, but the proper way to do it would be getting the uri from the FabricRuntime library, something similar to what is done in C# and java [here](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-connect-and-communicate-with-services#service-fabric-in-azure)
