### ISSUE TITLE
How do I run an Async workflow within a route handler

### ISSUE THREAD

**Issue by boeremak** [giraffe-fsharp/Giraffe#319]
Hi,

I've been getting to grips with Giraffe and while it works pretty awesomely for the most part I am having a hard time getting something from my mailbox processor.

I have the following code:
`let nodesRoute () = 
    fun (next:HttpFunc) (ctx:HttpContext) ->
        async {
            let! nodes =  processor.PostAndAsyncReply(fun reply -> GetNodes(reply))
            return nodes
        }
        |> ctx.WriteJsonAsync`

Which gets called like this:

`route "/api/nodes" >=> warbler (fun _ -> nodesRoute())`

But it always seems to return the Async object and not the result:
`{"result":[],"id":1,"exception":null,"status":5,"isCanceled":false,"isCompleted":true,"isCompletedSuccessfully":true,"creationOptions":0,"asyncState":null,"isFaulted":false}`

How do I get it to unpack the result?

I tried wrapping it in a Task and using StartAsTask but it doesn't seem to change anything. This is probably due to me not understanding how this all fits together but I haven't found anything that explains how I should run this.

**Comment by boeremak** [comment]
I figured it out, the writeJsonAsync also needs to run inside the task.

The following works:
`let nodesRoute () = 
    fun (next:HttpFunc) (ctx:HttpContext) ->
        task {
                let! nodes =  processor.PostAndAsyncReply(fun reply -> GetNodes(reply))
                return! ctx.WriteJsonAsync nodes
        }   `

Obvious when you think about it. 

Was a bit too soon with asking. Apologies.

**Comment by dustinmoris** [comment]
Hi, no worries it's never too soon to ask! Apologies that I didn't reply
sooner myself, I was just about to say that I'll have a look at this later
in the evening when I'm back home, but glad you already figured out what
you needed! :)
