### ISSUE TITLE
Feature request: execute and resolveService

### ISSUE THREAD

**Issue by Zaid-Ajaj** [giraffe-fsharp/Giraffe#333]
As we had discussed some ideas in #331, my main point was to hide implementation details of `HttpHandler` from the end user unless he/she really wants to build middleware themselves. My propostion of adding `handleContextAsync` didn't really make sense in the big picture of the library so here is an alternative that just might:

Let's assume the user had the function:
```fs
getAlbums : IMusicStore -> Task<Album list>
```
I want it to be really really simple to expose this through HTTP without thinking too much, I need:
- A way to get the *input* (`IMusicStore` in this case coming from IoC container) 
- A way to map the *output* (`Album list` as HTTP response)

Here is where `execute` and `resolveService` come into play with these types:
```fs
execute : Task<T> -> (T -> HttpHandler) -> HttpHandler
resolveService<'T>: ('T -> HttpHandler) -> HttpHandler
```
you can already tell where I am going with this :smile: 

First thing I have to think about is how to map the output of the function through Http, maybe map to JSON or return a Razor view etc.
```
mapAlbumsToJson : Album list -> HttpHandler = (* serialize to JSON for example *) 
``` 
then all I need to do it extract `IMusicStore` from the IoC container and chain the functions:
```fs
GET 
  >=> route "/albums"
  >=> resolveService<IMusicStore> (
      fun musicStore -> execute (getAlbums musicStore) mapAlbumsToJson
   )
```
if more parameters were needed like `albumId: int` then we would have used `routef` and passed in the path parameter to the function in question so no need for extra HTTP handler for extracting input. 

The names are of course subject to change (`execute` is probably too generic) but the I hope you get my idea. @dustinmoris I also like the `Giraffe.Experiemental` proposition but for these I would like to add them to `Core.fs` 

Let me know what you think!

**Comment by dustinmoris** [comment]
Hi, I think both handlers sound reasonable. Feel free to send a new PR for those!
