### ISSUE TITLE
routeStartsWithf missing?

### ISSUE THREAD

**Issue by NinoFloris** [giraffe-fsharp/Giraffe#341]
I'm working on Saturn routing right now and hitting a snag around the fact the tryMatchInput regex ends in $, could we add a flag to opt out of that? Then we could add some route functions (routeStartsWithCif and routeStartsWithf) on top to expose that

**Comment by dustinmoris** [comment]
Yes I suppose we could add a `(exactMatch : bool)` flag to the `tryMatchInput` function. Feel free to submit a PR!

**Comment by dustinmoris** [comment]
Out in 4.0.0
