### ISSUE TITLE
Are there any plans to support dotnet core 3?

### ISSUE THREAD

**Issue by rodrigodevelms** [giraffe-fsharp/Giraffe#362]
My team is starting a new NetCore project and we will use netcore 3 (do not do this, we accept the risks =)), and we wanted to use Giraffe. There are plans to launch a version that supports netcore 3, it may even be RC.

**Comment by TheAngryByrd** [comment]
What's stopping you from using Giraffe currently?

**Comment by slang25** [comment]
I've used it with preview versions and it's working great. I ran into this #351, but that's been fixed now. Let us know how you get on with your experience.

**Comment by slang25** [comment]
To be clear, that's Giraffe on AspNetCore 3, running on .NET Core 3

**Comment by rodrigodevelms** [comment]
im using Rider, with net core 3.0.100-preview5-011568.
And um getting this error: 
```
The specified framework 'Microsoft.AspNetCore.App', version '2.1.11' was not found.
  - The following frameworks were found:
      3.0.0-preview5-19227-01 at [/opt/net_core/sdk/shared/Microsoft.AspNetCore.App]
```

**Comment by dustinmoris** [comment]
I haven't discussed this with other maintainers yet, but personally I am always up for upgrading Giraffe to be supported on the latest stable ASP.NET Core version. I am currently a bit out of touch with the latest implications of ASP.NET Core 3 and not sure if an upgrade can be backwards compatible to .NET Core 2 or if this would be a breaking change. Let's use this issue to perhaps discuss any known issues/risks or other implications. If none then it's certainly a nobrainer, but either way, the plan should always be to run on the latest stable ASP.NET Core platform, unless something terrible happened, e.g. ASP.NET Core is PHP compiled into JavaScript, then compiled back into Mono and then run as an Electron app on Windows Server 2000. In this case we will burn everything and run away :)

**Comment by forki** [comment]
Using giraffe in dotnet core 3 works like a Charme and gives amazing perf. I already updated the TechEmpower benchmarks and the intermediate results are very promising.

**Comment by darting** [comment]
Is it about time? :)

**Comment by maxdeviant** [comment]
@slang25 I just upgraded our services to .NET Core 3.0 and ran into #351 as well. Do we have a general idea of when the next release of Giraffe might happen?

**Comment by dustinmoris** [comment]
Done!
