### ISSUE TITLE
Tests may no longer be valid in next release of AspNetCore3

### ISSUE THREAD

**Issue by panesofglass** [giraffe-fsharp/Giraffe#366]
[Pubternal APIs have been removed](https://github.com/aspnet/Announcements/issues/377) in the latest AspNetCore3.0. I noticed that the `Microsoft.AspNetCore.Internal` namespace is opened in some test files. You should either respond to [Fowler](https://twitter.com/filip_woj/status/1155192753699086355) or plan to change how tests are implemented.

- [ ] [HttpContextExtensionsTests.fs](https://github.com/giraffe-fsharp/Giraffe/blob/008674757698a1f931f679b2b9f3bcb554cac3f2/tests/Giraffe.Tests/HttpContextExtensionsTests.fs#L7)
- [ ] [ModelBindingTests.fs](https://github.com/giraffe-fsharp/Giraffe/blob/7981279dfef1432b271975449c8fcb5935cf977c/tests/Giraffe.Tests/ModelBindingTests.fs#L10)

https://github.com/aspnet/Announcements/issues/377

**Comment by slang25** [comment]
Thanks for the heads up 😃 I'll do some investigating. It looks like it's just `QueryCollection` we are using at the moment.

**Comment by slang25** [comment]
Looks like we can just remove the namespace once we upgrade.
https://github.com/aspnet/AspNetCore/pull/11429/files#diff-4ffa5b3e2cc2559caaf05c447c34f31e

**Comment by dustinmoris** [comment]
Out in 4.0.0

**Comment by panesofglass** [comment]
Thanks, @dustinmoris!
