### ISSUE TITLE
Implement routing as a request feature instead of using the Items collection

### ISSUE THREAD

**Issue by baronfel** [giraffe-fsharp/Giraffe#370]
Was talking with @NinoFloris and he mentioned that currently the routing information/subsystem is implemented using `HttpContext.Items`, which requires unboxing, lookups, etc.  It could be reimplemented using the `Features` concept (with the Items implementation as a fallback?) and sidestep most of those lookups. Implementations of Features that are included in ASP.Net Core can be found [here](https://github.com/aspnet/AspNetCore/tree/4ef204e13b88c0734e0e94a1cc4c0ef05f40849e/src/Http/Http/src/Features).

**Comment by NinoFloris** [comment]
Thanks for adding it :)

**Comment by slang25** [comment]
I had this thought a few months back when I read about `Features`, when I did the original subroutes logic I wasn't aware of it :(
It's a breaking change as custom handlers might rely on the underlying `HttpContext.Items` value, but it's worth doing it sooner than later.

**Comment by dustinmoris** [comment]
Agreed, it would be a welcome breaking change. I might have a stab at this myself!

**Comment by slang25** [comment]
It's also worth noting that Saturn knows about the `Items` `giraffe_route` key and behaviour. So it would make sense to follow up with a PR there, possibly a fallback in the behaviour there, i.e. if the feature is null then revert to the Items lookup.

**Comment by dustinmoris** [comment]
@slang25 Good point, thanks for bringing this to my attention!

**Comment by dustinmoris** [comment]
I'm closing this issue as we agreed in the PR which was actually addressing this issue that it was not the right thing to do. Please feel free to re-open if you disagree!
