### ISSUE TITLE
Support for rendering Blazor components with Giraffe View Engine

### ISSUE THREAD

**Issue by OnurGumus** [giraffe-fsharp/Giraffe#371]
Razor can render Blazor components either by embedding as a tag or utilizing
**Html.RenderComponentAsync** method. What is the solution for Giraffe View Engine?

**Comment by dustinmoris** [comment]
Hi, I haven't tried Blazor with Giraffe yet. Blazor is just a way to render Razor in web assembly. The `GiraffeViewEngine` is its own view engine and I don't think anyone has looked at how to use it from web assembly yet, but would be nice if someone tried it out. Razor on the other hand is supported in Giraffe through the `Giraffe.Razor` NuGet package (and GitHub repo) and you should be able to use `Html.RenderComponentAsync` via `Giraffe.Razor` so potentially there is already a way to use Blazor from/with Giraffe.

Maybe have a play with `Giraffe.Razor` and open any issues [in the repo](https://github.com/giraffe-fsharp/Giraffe.Razor) if you think that something isn't working as expected.

**Comment by OnurGumus** [comment]
Actually, looking at the implemetnation it looks like doable:
```
            var httpContext = htmlHelper.ViewContext.HttpContext;
            var serviceProvider = httpContext.RequestServices;
            var prerenderer = serviceProvider.GetRequiredService<StaticComponentRenderer>();

            var parametersCollection = parameters == null ?
                ParameterView.Empty :
                ParameterView.FromDictionary(HtmlHelper.ObjectToDictionary(parameters));

            var result = await prerenderer.PrerenderComponentAsync(
                parametersCollection,
                httpContext,
                typeof(TComponent));

            return new ComponentHtmlContent(result);
```

**Comment by dustinmoris** [comment]
Am I right to assume that Blazor should just work with Giraffe and this can be closed? If yes, do you have an example which can be shared with the community by either linking here or to the documentation?

**Comment by OnurGumus** [comment]
No I have not tried it. I have no idea if it works or not.

**Comment by dustinmoris** [comment]
I'm closing this issue. If Blazor does *not* work with Giraffe then please re-open again!
