### ISSUE TITLE
Use FileShare.Read for HttpContext.WriteFileStreamAsync

### ISSUE THREAD

**Issue by cmeeren** [giraffe-fsharp/Giraffe#376]
Here are the final two lines of `WriteFileStreamAsync`:

https://github.com/giraffe-fsharp/Giraffe/blob/6e33155d3f0929af52886a7302fbd12a07ff9cb7/src/Giraffe/Streaming.fs#L231-L232

According to [the `FileShare` enum docs](https://docs.microsoft.com/en-us/dotnet/api/system.io.fileshare?view=netframework-4.8), the default value of that enumeration is `None`, which has this description:

> Declines sharing of the current file. Any request to  open the file (by this process or another process) will fail until the  file is closed.

It could of course be that `FileStream` sets another default value, but I haven't been able to find any information on that in the FileStream docs.

It then seems to me that `WriteFileStreamAsync` will make any request to the same file fail for as long as the previous request is still processing, which can of course take a while.

If this is correct, I suggest adding a `FileShare.Read` parameter to the `FileStream` constructor to enable multiple requests to read at the same time:

```diff
-use stream = new FileStream(filePath, FileMode.Open, FileAccess.Read)
+use stream = new FileStream(filePath, FileMode.Open, FileAccess.Read, FileShare.Read)
```

**Comment by slang25** [comment]
It looks like if it's not specified then `FileShare.Read` will be used: https://github.com/dotnet/corefx/blob/master/src/Common/src/CoreLib/System/IO/FileStream.cs#L15

**Comment by cmeeren** [comment]
Thanks, this is a non-issue then.
