### ISSUE TITLE
Remove dependency on deprecated packages

### ISSUE THREAD

**Issue by forki** [giraffe-fsharp/Giraffe#377]
https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-3.0&tabs=visual-studio#remove-obsolete-package-references

    Giraffe (4.0)
      FSharp.Core (>= 4.7) - restriction: || (>= net461) (>= netstandard2.0)
      Microsoft.AspNetCore.Authentication (>= 2.2) - restriction: || (>= net461) (>= netstandard2.0)
      Microsoft.AspNetCore.Authorization (>= 3.0) - restriction: || (>= net461) (>= netstandard2.0)
      Microsoft.AspNetCore.Diagnostics (>= 2.2) - restriction: || (>= net461) (>= netstandard2.0)
      Microsoft.AspNetCore.Hosting.Abstractions (>= 2.2) - restriction: || (>= net461) (>= netstandard2.0)
      Microsoft.AspNetCore.ResponseCaching (>= 2.2) - restriction: || (>= net461) (>= netstandard2.0)
      Microsoft.IO.RecyclableMemoryStream (>= 1.2.2) - restriction: || (>= net461) (>= netstandard2.0)
      Newtonsoft.Json (>= 12.0.2) - restriction: || (>= net461) (>= netstandard2.0)
      System.Text.RegularExpressions (>= 4.3.1) - restriction: || (>= net461) (>= netstandard2.0)
      System.ValueTuple (>= 4.4) - restriction: >= net461
      System.ValueTuple (>= 4.5) - restriction: && (< net461) (>= netstandard2.0)
      System.Xml.XmlSerializer (>= 4.3) - restriction: || (>= net461) (>= netstandard2.0)
      TaskBuilder.fs (>= 2.1) - restriction: || (>= net461) (>= netstandard2.0)
      Utf8Json (>= 1.3.7) - restriction: || (>= net461) (>= netstandard2.0)

so please remove deps to Microsoft.AspNetCore.*

**Comment by slang25** [comment]
That would require us to switch completely over to `netcoreapp3.0`, dropping `netstandard2.0` and `net4x`, might be the right time to do it.

**Comment by forki** [comment]
Go for it.


Stuart Lang <notifications@github.com> schrieb am Mo., 30. Sep. 2019, 10:15:

**Comment by slang25** [comment]
@forki WIP here: #378

**Comment by dustinmoris** [comment]
Maybe we can keep support for net461 and netcoreapp2.0 for just a bit longer as not everyone has immediate time to switch to the latest framework, but otherwise I agree let's always make sure Giraffe is on the latest with all the recommendations and deprecate support for the other frameworks at the latest by the time MS also stops supporting them. For now, I'd suggest to remove these packages through conditions in the .fsproj file and #ifdefs in code where necessary.

**Comment by slang25** [comment]
Agreed, updated: #378

**Comment by forki** [comment]
ok serious question: is there anyone not using netcore for giraffe?

**Comment by slang25** [comment]
I would bet not a single soul 😆 Here it doesn't cost us anything on top of ns2.0 IMO

**Comment by dustinmoris** [comment]
@forki I hope not :), but you never know!

**Comment by forki** [comment]
Yes but those can happily use giraffe 4. Forever

Dustin Moris Gorski <notifications@github.com> schrieb am Mo., 30. Sep.
2019, 11:51:

**Comment by maxdeviant** [comment]
> ok serious question: is there anyone not using netcore for giraffe?

I didn't even realize you could use Giraffe with .NET Framework.

**Comment by NinoFloris** [comment]
netcoreapp 2.1 will be LTS for another 2 years, I think that should be the minimum bar.

**Comment by forki** [comment]
@NinoFloris it doesn't seem possible to support both frameworks with one giraffe package.

**Comment by forki** [comment]
for netcore 2.2 we need to reference those packages from giraffe. 
for netcore 3 we should not because they no longer exist for that version

so we could in theory add different dependency groups for netcoreapp3 and nectoreapp2.2 in the nuspec of Giraffe. But how does this work with being netstandard2.0? 

It's pretty much fucked up.

**Comment by slang25** [comment]
It's not great I'll admit, but do you have any particular objection to this:
https://github.com/giraffe-fsharp/Giraffe/blob/develop/src/Giraffe/Giraffe.fsproj#L46-L56

**Comment by forki** [comment]
The problem is that we are netstandard lib. It's totally unclear what's
happening downstream

Stuart Lang <notifications@github.com> schrieb am Do., 17. Okt. 2019, 12:21:

**Comment by NinoFloris** [comment]
As I see it it's pretty 'simple' netcoreapp3.0 has precendence over netstandard2.0. 

Hence netstandard should just references all the packages like it did, and netcoreapp3.0 should only have a framework reference + supplemental extension packages etc. 

That's exactly how it's setup right now.

**Comment by forki** [comment]
That's not completely correct. There are compiled references into concrete dlls. The platform resolver needs to find the exact corresponding dlls. And it's up to luck that this works.

That said: we should release a version with the proposed changes so that we can try out if it works. Also saturn will need it

**Comment by forki** [comment]
My assumption is that the proposed change will just work as long as the sdk ships dlls witj same name and same signatures of the stuff that we use

**Comment by NinoFloris** [comment]
What's not completely correct? It's a simplification of all the involved parts but I believe it's not wrong.

The fact you can have restore resolving different concrete dll deps for Giraffe that are not actually referenced in the concrete Giraffe dll for that TFM is an implementation detail and a bug if it goes wrong no?

**Comment by forki** [comment]
Giraffe compiles against something in aspnet 2.2. As in calling a method in
somthing.dll. There is no guarantee that this method exists in 3.0. It's
not even clear if something.dll even exists anymore.



Nino Floris <notifications@github.com> schrieb am Do., 17. Okt. 2019, 12:38:

**Comment by NinoFloris** [comment]
That's why we multi target though.

And to continue my previous comment, multi targetting would be entirely useless if restore didn't at least try to keep restore deps (which ends up in publish) vs concrete dll deps mismatches from happening. 

Now the fact FrameworkReferences aren't actually participating in version unification (in nuget) is a whole other fun part and I consider it very bad. It means that packages you reference in your project that aren't already recompiled for netcoreapp3.0, and you have a FrameworkReference in your proj (courtesy of web sdk) it won't warn you during restore that FrameworkReference Microsoft.AspnetCore.App is not compatible with package that references Microsoft.AspnetCore.App 2.2 as a package reference. That part is garbage...

**Comment by forki** [comment]
The thing is: we should try it out. I'd appreciate a new release and
volunteer for testing it immediately.

Nino Floris <notifications@github.com> schrieb am Do., 17. Okt. 2019, 12:47:

**Comment by NinoFloris** [comment]
What should be changed? @slang25 your changes went in during 4.0 right? @forki does 4.0 work with newestget on core 3.0?

**Comment by slang25** [comment]
No, we need to do another release to satisfy @forki concerns.

**Comment by forki** [comment]
@Ninofloris the current released package unconditionally references 2.2 stuff.

**Comment by slang25** [comment]
Looks like @dustinmoris has done a new release:
https://github.com/giraffe-fsharp/Giraffe/releases/tag/v4.0.1

Thanks Dustin 👍

**Comment by forki** [comment]
![image](https://user-images.githubusercontent.com/57396/67115446-83eea680-f1de-11e9-9fd0-08320da6c24a.png)

looks like it's working. Thanks

**Comment by forki** [comment]
Corresponding TechEmpower PR: https://github.com/TechEmpower/FrameworkBenchmarks/pull/5162

**Comment by atlemann** [comment]
Is it possible to do these conditional package references with Paket?

**Comment by forki** [comment]
If you do manual template files.
