### ISSUE TITLE
Is there a Giraffe Elmish example?

### ISSUE THREAD

**Issue by olawdy** [giraffe-fsharp/Giraffe#385]
Hi!

My company is interested in evaluating Giraffe for a custom web server backend, but I'm not sure if there is a Giraffe implementation for Elmish. Currently we have a sample web app up and running based on this example here -

https://github.com/The-Dev-Owl/dev-owl-todo-application

However, we might rather use a Giraffe backend instead of the Node backend that the current example comes with.

Please advise :)

**Comment by theimowski** [comment]
You might wanna look at https://safe-stack.github.io/

**Comment by dustinmoris** [comment]
As mentioned above Giraffe works well with Elmish as part of the SAFE stack :)
