### ISSUE TITLE
redunancy in return early example

### ISSUE THREAD

**Issue by Git-Tri** [giraffe-fsharp/Giraffe#386]
Hi,

In the return early section of the documentation, it uses this line of code (as part of the example) to demonstrate cutting a pipeline off early:

(setStatusCode 401 >=> text "Please sign in.") finishEarly ctx

In this example however, the finishEarly call would never actually be called as the text httphandler does not call the next function in the pipeline anyway. So if you debugged the code, the finishEarly httpFunc would not be called. 

I'm not sure if this warrants a change as it still demostrates the idea, but it can be confusing if the programmer using the example debugs the code, which is how i found it. So i opened this as a "just case you didn't know" issue. 

Thanks for the great framework :smiley:

**Comment by dustinmoris** [comment]
Good point, I'll try to make that change in the docs when I touch it again!
