### ISSUE TITLE
Add example using generic host to documentation

### ISSUE THREAD

**Issue by LiteracyFanatic** [giraffe-fsharp/Giraffe#388]
The ASP.Net Core 3.0 documentation recommends using the generic host instead of the web host. As someone new to both Giraffe and ASP.Net in general, it took me awhile to figure out how to do that. I think an example using `CreateDefaultBuilder` and `ConfigureWebHostDefaults` would make a good addittion to Giraffe's documentation unless there is some reason to prefer the web host.

**Comment by dustinmoris** [comment]
Hi, agreed, please feel free to submit a PR or a snippet of additional documentation in this issue which you would like me to add to the docs! Thank you!

**Comment by LiteracyFanatic** [comment]
Looks great. Thanks for taking the time to add that!
