### ISSUE TITLE
netcoreapp3.1 with Azure Functions

### ISSUE THREAD

**Issue by Dzoukr** [giraffe-fsharp/Giraffe#390]
Hello Dustin,

I found strange issue so maybe you could help (or redirect me somewhere else).

I was successful with running Giraffe on Azure Functions V3 on `netcoreapp3.0` without any problem. But changing target framework to `netcoreapp3.1` triggers issue during host startup:

`Could not load file or assembly 'Microsoft.Extensions.DependencyInjection.Abstractions, Version=3.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.`

Please see repo I created just for this issue: https://github.com/Dzoukr/Issues/tree/master/FunctionsGiraffe (don't forget to change target framework to see issue during host startup)

Is it because the highest dependency on Nuget for Giraffe is `netcoreapp3.0`?

Azure Funcs Core Tools version: 3.0.1975

Thanks for any help! 🙏

**Comment by forki** [comment]
giraffe works fine with netcoreapp3.1 - I'm running it.
Azure Functions does not work with 3.1 yet

**Comment by Dzoukr** [comment]
The repo I sent works ok with netcoreapp3.1 (sdk & tools are about 20hrs old), but not with Giraffe.

**Comment by Dzoukr** [comment]
It seems I took tools before announcement, but Azure Funcs for 3.1 are now GA https://github.com/Azure/app-service-announcements/issues/220.

So this use case (Giraffe + Funcs v3) should be valid now.

**Comment by Dzoukr** [comment]
You know, sometimes the real cause of many of my problems is, that I am an idiot. 😄 

_** silently searching for "Delete whole issue and pretend it never happened" button **_

It works like a charm and thanks @forki for helping me over Twitter to get to it!! 🙏
