### ISSUE TITLE
Model binding of query strings does not work for arrays

### ISSUE THREAD

**Issue by nickkossolapov** [giraffe-fsharp/Giraffe#403]
With the model 
```
[<CLIMutable>]
type SearchRequest = {
    searchTerms = string[]
}
```
trying to bind a collection in a query string to the array on the model, e.g. `localhost:8084??searchTerms=search1&searchTerms=search2`, the binding fails and the array is set to null.

When the model is changed to use a list, e.g.
```
[<CLIMutable>]
type SearchRequest = {
    searchTerms: string list
}
```
the binding works correctly. It seems that arrays are not catered for in `ModelBinding.parseValue`

**Comment by dustinmoris** [comment]
Thanks for raising this issue. I'll try to get this fixed for the next bigger release!
