### ISSUE TITLE
Feature request: Move Giraffe.GiraffeViewEngine into its own assembly

### ISSUE THREAD

**Issue by reinux** [giraffe-fsharp/Giraffe#406]
It would be nice to have GiraffeViewEngine in its own assembly, with fewer dependencies, so that we can move view code into separate assemblies and speed up compiling. As it stands, `dotnet watch` takes 8-10 seconds on my (old-ish) machine.

Disscused in #93  .

**Comment by bradder555** [comment]
This is something I'm keen for, can you assign this to me and I'll put together a PR?

**Comment by dustinmoris** [comment]
@bradder555 I've created two new repos:

- `Giraffe.ViewEngine`
- `samples`

Feel free to put any necessary PRs together in all affected repos. You will have to remove all mentions of the `GiraffeViewEngine` in the main repo, then you'll have to create a new project inside the `Giraffe.ViewEngine` repo from where we can build a new NuGet package for the moved code and finally you might even have to move all the sample projects into the new `samples` repo, as most sample applications in the main repo rely on the `GiraffeViewEngine` and I don't want to create circular dependencies.

Let me know if you're still keen on this work. I'm also happy to help!

**Comment by bradder555** [comment]
Awesome, thanks for that!

I'll get started and see how I go. 

Pretty pumped you're supportive of it.

Cheers, Brad

**Comment by dustinmoris** [comment]
@bradder555 Thank you, I'm really thankful for contributors like yourself who help to make Giraffe constantly better! I'll do anything I can do to help others to contribute as it's a massive help for me!

**Comment by dustinmoris** [comment]
So I've started to do some of the boring work of moving all the sample applications out of the  main repo and into the `samples` repo. That's done.

**Comment by reinux** [comment]
Thank you very much!

**Comment by dustinmoris** [comment]
I have also created a new branch here called `release/5.0.0-alpha-001`. This branch has removed support for .NET Framework 461 and I've also removed everything which had a reference to the `GiraffeViewEngine`.

The removal is done in a single commit, which you can use as a reference to know what has to be moved into the new repo: https://github.com/giraffe-fsharp/Giraffe/commit/3590f4742196845aa3683e72ad439b41abbd58d5

That leaves now just the work to create a new project for the view engine. I am about to finish for today and leave that up to you to give it a head start there!

**Comment by reinux** [comment]
@dustinmoris Just saw your last comment on the other issue.

Are the XmlNode types being brought in from Giraffe? I'm assuming this is the main point of concern, that the html functions would end up having a bunch of `'a`s and `'b`s which only ever map to XmlNodes and XmlAttributes.

If that's the case, I suppose it could potentially even become the foundation for other F# view engines as well, e.g. Fable and Bolero -- though I can see why it might be a little ugly.

From what I understand of what Phillip Carter explained, it's the fact that Giraffe has a lot of other dependencies that makes any assemblies compiling from it take particularly long. So I _think_ not having any Giraffe dependencies would be ideal.

From the [fsharp subreddit](https://www.reddit.com/r/fsharp/comments/fiz2l7/still_struggling_with_slow_compiling/fkmfbtf/):

> Giraffe pulls in a lot of dependencies that need to be referenced. There's a lot of overhead with that. Firstly, a performance summary for a new giraffe app on my machine shows nearly 1 second spend in MSBuild tasks associated with resolving and managing the metadata references it uses. The F# compiler then also spend 3.5s compiling. A good chunk of that is actually importing those metadata references and turning them into typed trees so that they can be typechecked against. The more metadata references, the more time is spent doing all of this. For example, on a clean build of a console app,the ResolveAssemblyReferences task in MSBuild took 46ms. For a clean build of a new giraffe template, it took 320ms. That's pretty significant!
>
> One thing that can help - to a degree - is breaking things out into multiple projects. There's this habit in much of the F# community of stuffing everything into one giant project with a few very small "head" projects. A downside to this is that recompile times generally take longer, whereas recompiling only one project out of 10 is significantly cheaper. This approach does also increase MSBuild overhead, though, and if you have 120 or more projects in a solution that overhead is pretty significant. But I'd also say that once you're in that territory you're going to have long build times no matter what happens (as a fun exercise, try building Roslyn.sln and see how long it takes!)

**Comment by dustinmoris** [comment]
> Are the XmlNode types being brought in from Giraffe?

No that is basically what comes with the `GiraffeViewEngine`, so this will be part of the new NuGet package now. Nothing else in Giraffe uses these types except the `GiraffeViewEngine`.

> So I think not having any Giraffe dependencies would be ideal.

Yeah from what you said I thought that would be required. It's possibe but then we might have to still define the view engine http handlers in the main `Giraffe` package. So essentially `Giraffe.ViewEngine` would have zero dependencies and `Giraffe` would actually have a dependency on `Giraffe.ViewEngine`. Otherwise `Giraffe.ViewEngine` would have to reference some ASP.NET Core packages which would be annoying I guess given that the goal is to reduce the assembly number.

**Comment by reinux** [comment]
> Otherwise Giraffe.ViewEngine would have to reference some ASP.NET Core packages which would be annoying I guess given that the goal is to reduce the assembly number.

That's my understanding. So if the views can be compiled in a small assembly that only references `GiraffeViewEngine` and whatever other stuff that's needed for the views (in my experience so far, basically nothing)`, it ought to speed up tinkering with the html quite a bit.

It might also have the added benefit of helping people who aren't too familiar with F# understand view code without being overwhelmed by the handler and hosting stuff. That could make it a lot easier to ask for broader help with UI design.

I just took a quick look at where `HttpContext` comes from: it's defined in `Microsoft.AspNetCore.Hosting.Abstractions`, which seems simple enough, but that in turn references three other packages suffixed with `Abstractions`, and from there it just sprawls. So isolating handlers in yet another package might yield fairly diminished returns.

I think that's all right, though, since it's always been the case with ASP.NET (since at least MVC) that changing handlers/controllers/etc took longer than changing the html.

**Comment by dbrattli** [comment]
This would be great as the [Feliz.ViewEngine](https://github.com/dbrattli/Feliz.ViewEngine) can also now be used witn Giraffe instead of GiraffeViewEngine. Feliz.ViewEngine is based on the same "engine" but adaped for Feliz DSL. I first wanted to call it Feliz.Giraffe or Giraffe.Feliz but renamed it to ...ViewEngine since we ended up not have any deps on Giraffe.

**Comment by bradder555** [comment]
I've raised a PR if you'd like to take a look :) [PR1](https://github.com/giraffe-fsharp/Giraffe.ViewEngine/pull/1)

**Comment by Krzysztof-Cieslak** [comment]
Maybe it would be good to introduce some kind of `IXmlNode` interface (with a method `ToHtmlString`) that could be used by both Giraffe.ViewEngine and Feliz.ViewEngine? This way we could program against interface just like in a case of Serializers and users could plug whichever ViewEngine they want easily?

**Comment by bradder555** [comment]
Wouldn't IHtmlString be more appropriate? The interface doesn't really care
'how' the htmlString is generated, merely that it implements ToHtmlString
() -> string.

It'll be nice to have a IHtmlAsciiBytes, IHtmlUtf8Bytes too.

Ultimately, the serialised page should be thought of as a binary blob and
should be guarded (since any charges after serialisation would likely lead
to corruption)

Maybe a new type HtmlBlob?
type HtmlBlob = | HtmlBlob of string
  member blob.ToStream() =
    ...
  member blob.ToSeq() =
    ...

**Comment by dustinmoris** [comment]
I've released a first version of `Giraffe.ViewEngine` today and a new pre-release of Giraffe using it.

Regarding the generic interface please open an issue over at the [Giraffe.ViewEngine](https://github.com/giraffe-fsharp/giraffe.viewengine/) project.

Many thanks everyone for your input!

**Comment by reinux** [comment]
Thank you! Just grabbed it.

The detailed documentation is much appreciated too.

And I can already think of several uses for `RenderView.AsString`.
