### ISSUE TITLE
Make giraffe-template an independent project

### ISSUE THREAD

**Issue by bradder555** [giraffe-fsharp/Giraffe#408]
Hi There

Ultimately, the giraffe-template takes HTTP types and renders them into text or bytes.

This could stand on its own two feet as a templating language instead of having any giraffe dependencies.

I propose stripping giraffe dependencies and interfaces.

Perhaps a new project containing the templating -> giraffe shim could be created?

**Comment by dustinmoris** [comment]
Ah now that makes sense :)
Yes there's already an issue for that, I think I am considering to split it out into its own NuGet packages. See #406.

I'm closing this issue as a duplicate and the discussion should continue in #406, but me closing this doesn't mean that I'm not doing it. It seems to be a good suggestion.
