### ISSUE TITLE
Question: how to pass arbitary type of custom data to next handler

### ISSUE THREAD

**Issue by lanyusan** [giraffe-fsharp/Giraffe#425]
I have started to use Giraffe on a project. It is a great experience. Thanks for this amazing library.

I have a question about handler chaining. I somehow want to design handlers that each one will do some work, generate some interim data and next one can pick the interim data and continue the processing. In other none functional frameworks, it is easy because handlers can add new keys with data to request or response object or context object such as Express in Nodejs.

I couldn't find a way to do it through reading documentation or searching issues. 
I know that such a pattern could be done through function chaining within handler but if it is able to do so easily by passing arbitrary type of custom data  it could open up new ways for handler design and composition.

Thanks in advance.

**Comment by baronfel** [comment]
@ninjarobot has a gist with the exact use case that you can use: https://gist.githubusercontent.com/ninjarobot/96103006466d97e7cbc50456e0b5c5e2/raw/47e28e619d4e82b186fd91fe8e23675646f3899a/ExampleTypedWebParts.md

**Comment by lanyusan** [comment]
@baronfel Thanks.

**Comment by TheAngryByrd** [comment]
Closing as this has been answered
