### ISSUE TITLE
Websockets support

### ISSUE THREAD

**Issue by forki** [giraffe-fsharp/Giraffe#432]
I ported SignalR style middleware to F# so that we can hook websockets in. I think I want to OSS it and if people think it's Ok then we could do it as Giraffe.Websockets. Such things doesn't exist yet, right?

**Comment by dustinmoris** [comment]
Cool! Have you got an example somewhere to look at?

Is this meant to be a replacement for [this PR](https://github.com/giraffe-fsharp/Giraffe/pull/182)?

**Comment by drhumlen** [comment]
@forki : What's the status on this? It would be nice to have this merged asap 😄

**Comment by dustinmoris** [comment]
I'm going to close this issue as it went a bit stale. ASP.NET Core has web socket support and it can be done in F#. I have currently not the time to work out what a functional first world of web sockets in ASP.NET Core would look like and therefore don't see myself work on this feature in the near or mid term future. I'm more than happy for help and PRs if someone wants to take on the work though.

**Comment by TheAngryByrd** [comment]
For anyone in the future, I have a repo https://github.com/TheAngryByrd/FSharp.Control.WebSockets that I would advise people to use as their base for any hub/messaging.
