### ISSUE TITLE
How can I use a type with an int option field when I use BindJson

### ISSUE THREAD

**Issue by idarous** [giraffe-fsharp/Giraffe#438]
I want to bind a payload that I receive with this instruction `ctx.BindJsonAsync`

However I have a field of type `int option`

Here is my type

```
type Info =
    { rank : int option
      value : string }
```

The code can be compiled but when I pass a JSON value from my HTTP  client like that it works well
```
{
  "rank": null,
  "value": "val1"
}
```

But I cannot pass a value in my field rank like that it doesn't work
```
{
  "rank": 5,
  "value": "val1"
}
```
What is the correct way to pass a nullable int value and handle it with the method `BindJson` ?

**Comment by slang25** [comment]
@idarous the way it works in Giraffe is you set the serializer and its settings, and `BindJson` will use that to deserialize. [Docs](https://github.com/giraffe-fsharp/Giraffe/blob/master/DOCUMENTATION.md#json)

The default serializer is `NewtonsoftJsonSerializer`, and you could add some F# friendly converters to make it work with `option` (I'd need to google it tbh). My preferred approach is to use `System.Text.Json` & `FSharp.SystemTextJson` (with the `FSharpLuLike` option configured), which IMO gives you intuitive defaults and supports F# idioms. Alternatively, you could use `CompactUnionJsonConverter` from `Microsoft.FSharpLu`.

You will find examples of both here in the docs:
https://github.com/giraffe-fsharp/Giraffe/blob/develop/DOCUMENTATION.md#json

Let me know if you have any issues 🙂

**Comment by dustinmoris** [comment]
Closing since it looks to have been solved.
