### ISSUE TITLE
Suggestion for view engine, add Feliz synthax

### ISSUE THREAD

**Issue by jkone27** [giraffe-fsharp/Giraffe#444]
just a proposal/suggestion: Feliz Synthax is way more straight forward for HTML templating, 
https://github.com/Zaid-Ajaj/Feliz

instead of writing (or as an alternative, e.g. ViewEngine.FelizStyle?)
```fsharp
div [ ] [
    div [ ] [ text "hello" ]
]
```
we could write
```fsharp
Html.div [
    prop.children [
        Html.div "hello"
    ]
]
```
but maybe is very complex to implement

Moving this to viewengine repo, sorry

**Comment by TheAngryByrd** [comment]
[Answered on that repo](https://github.com/giraffe-fsharp/Giraffe.ViewEngine/issues/5#issuecomment-679137809)
