### ISSUE TITLE
Add C# interoperaility

### ISSUE THREAD

**Issue by Lanayx** [giraffe-fsharp/Giraffe#445]
Right now it's impossible to use any giraffe HttpContext extensions because they are added as F# extensions. I suggest to add them as general .NET Extension methods. With that it will be possible to use Giraffe in C# applications built with endpoint routing plus Giraffe extensions.

**Comment by dustinmoris** [comment]
Is there a way to do this in F# or does that involve to create a C# project?

**Comment by baronfel** [comment]
Yeah, F# can do them. Docs are [here](https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/type-extensions#extension-methods), the gist is that you make static members on a class and add some marker interfaces.
