### ISSUE TITLE
Endpoint: subRoute ignored with nested http verb - 5.0.0-rc-3

### ISSUE THREAD

**Issue by pkuo** [giraffe-fsharp/Giraffe#452]
`let endpoints =
    [ subRoute "/sub" [ GET [ route "/test" handler1 ] ] ]`

The resulting endpoint is "/test" not "/sub/test".

This however works:
`let endpoints =
    [ GET [ subRoute "/sub" [ route "/test" handler1 ] ] ]`

**Comment by dustinmoris** [comment]
Thanks for reporting this issue. I've applied a fix which will be released in the coming days as part of the next RC iteration.

**Comment by dustinmoris** [comment]
Fix: https://github.com/giraffe-fsharp/Giraffe/commit/c3922b9264dccb3e416125146d6e00114aeb12f5

**Comment by dustinmoris** [comment]
Fixed with latest release. Thanks for reporting!
