### ISSUE TITLE
How to add RequestSizeLimit attribute like in asp.net core c#

### ISSUE THREAD

**Issue by naughtyGitCat** [giraffe-fsharp/Giraffe#463]
need to increase the RequestSizeLimit, to receive a larger multipart form file uploads

**Comment by dustinmoris** [comment]
Request limits are specified by Kestrel (= ASP.NET web server) and any other infrastructure between your API and the end user. Check [here on how to change the request limit for Kestrel](https://stackoverflow.com/questions/46738364/increase-upload-request-length-limit-in-kestrel). If you have other infrastructure pieces between Kestrel and the user (e.g. nginx, load balancers, etc.) then you will have to check with the vendor which limits they have and how to change them.
