### ISSUE TITLE
.net 5

### ISSUE THREAD

**Issue by padzikm** [giraffe-fsharp/Giraffe#471]
Hi, when will be release for .net 5? giraffe is in .net 5 rc for some time and I can't find any new about moving it forwards.

**Comment by l3m** [comment]
What's the state of this? I noticed that the latest RC is from December 2020. 

Are there any blockers for a non-RC net5.0-based release? Anything I can help with?

**Comment by dustinmoris** [comment]
To be honest there are no real blockers I was simply hoping to get some feedback on the newer Endpoint Routing API but either there are literally on issues with it or people have not used it yet. I agree though, time to release. I'll aim for next weekend where I'll go through all remaining issues and initiate a stable release.

**Comment by travis-leith** [comment]
I think there are a bunch of people using this on the safe stack .net5 (yet to be officially released) version. Apparently no issues have been reported. My understanding is that once this officially supports .net, the safe stack folks will do so too.

**Comment by Zaid-Ajaj** [comment]
Hi @dustinmoris any chance you can push a stable release? Got a bunch of libraries depending on Giraffe and would be great if we are able to upgrade them to latest stable 🙏

**Comment by dustinmoris** [comment]
@Zaid-Ajaj Done!

/cc @isaacabraham

https://www.nuget.org/packages/Giraffe/5.0.0

**Comment by Zaid-Ajaj** [comment]
Thanks a lot @dustinmoris 🙏
