### ISSUE TITLE
Question: Authentication for the new Endpoint Routing

### ISSUE THREAD

**Issue by nasko90** [giraffe-fsharp/Giraffe#480]
Hello guys,
I failed to find any information/documentation about how one could implement the Authentication with ASP.NET Core's Endpoint Routing. Is it possible to use the requiresAuthentication (authFailedHandler : HttpHandler) http handler.
Thanks!

**Comment by dustinmoris** [comment]
Hi, yes you should still be able to use that handler for an endpoint.

**Comment by ilog2000** [comment]
Hello, would you mind to give an example? Let's imagine this router
```f#
open Giraffe
open Giraffe.EndpointRouting

module Router =
    let endpoints : Endpoint list = [
        route "/ping"  (text "pong")
        route "/"         (text "index")
        subRoute "/protected" [
            GET [
                route "/hello" (text "hello")
            ]
        ]
    ]
`''
How can I use `requiresAuthentication` on protected sub-route?

**Comment by Banashek** [comment]
@ilog2000 

You can compose it into the route list similar to other handlers:

```fs
let webApp =
    choose [
        route "/ping"   >=> text "pong"
        route "/"       >=> htmlView indexView
        requiresAuthentication (text "failed") >=>
            subRoute "/protected"
                (choose [
                    GET >=> choose [
                        route "/hello" >=> text "hello" ]])]
```

**Comment by ilog2000** [comment]
@Banashek , thank you very much. I really like this solution - it's clear and well separated into specific areas. And I did not know about `applyBefore`.

**Comment by 64J0** [comment]
Hey people, I'm considering that @dustinmoris and @Banashek already answered this issue, so I'll close it with this comment. If you think there's still something lacking, please open a new issue so we can investigate it properly.
