### ISSUE TITLE
setContentType function

### ISSUE THREAD

**Issue by Choc13** [giraffe-fsharp/Giraffe#483]
I've found myself searching for a `setContentType` function, like `setStatusCode` that is just a functional version of the `SetStatusCode` extension method on `HttpContext`. 

I couldn't find this one, am I right in thinking it doesn't exist?

If not would you be happy for me open a PR to add it to `Core.fs` alongside `setStatusCode`?

I believe the implementation is just

```fsharp
let setContentType contentType : HttpHandler =
    fun next ctx ->
        ctx.SetContentType contentType
        next ctx
```

**Comment by esbenbjerre** [comment]
@64J0 I believe this issue can be closed.
