### ISSUE TITLE
[Question] I can't figure out how to change the port

### ISSUE THREAD

**Issue by arnesahlberg** [giraffe-fsharp/Giraffe#486]
How do I change the port the web app is running on? 

I've tried changing the ports given in the configureCors method, but it doesn't seem to do anything. 

`let configureCors (builder : CorsPolicyBuilder) =
    builder
        .WithOrigins(
            "http://localhost:5000",
            "https://localhost:5001")
       .AllowAnyMethod()
       .AllowAnyHeader()
       |> ignore`

**Comment by peterhirn** [comment]
see https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/web-host?view=aspnetcore-5.0#server-urls

    webHostBuilder
        .UseUrls("http://localhost:1234")

**Comment by dustinmoris** [comment]
Thanks for answering the question @peterhirn!
