### ISSUE TITLE
feature request for documentation: add test examples

### ISSUE THREAD

**Issue by draptik** [giraffe-fsharp/Giraffe#489]
As user of this framework I would like some guidance / best practices for writing tests.

What are typical integration or unit tests one might write (with examples in documentation)?

In C# one might consider using the `WebApplicationFactory<T>` approach.

https://docs.microsoft.com/en-us/aspnet/core/test/integration-tests?view=aspnetcore-5.0

Is also reasonable here?

Don said it's ok to mention this tweet: https://twitter.com/dsymetweets/status/1417417949233795082

**Comment by dustinmoris** [comment]
Giraffe has a section on [Testing in the docs](https://github.com/giraffe-fsharp/Giraffe/blob/master/DOCUMENTATION.md#testing).

**Comment by dustinmoris** [comment]
Please let me know if you think there is anything missing or confusing in ASP.NET Core which is specific to Giraffe. Feel free to re-open in that case! Thanks for filing the issue and helping to make Giraffe better!
