### ISSUE TITLE
F# 6 task CE namespace conflict with Ply

### ISSUE THREAD

**Issue by NinoFloris** [giraffe-fsharp/Giraffe#490]
F# 6 will ship with a task implementation under FSharp.Control.Tasks (with an auto open for the TaskBuilder module). Ply uses the same namespace, these are going to conflict. Thanks @dsyme for noticing it!

My suggestion would be to do a major version bump for 6.0 and create a conditional package reference for Ply on the net6.0 TFM. Note, this doesn't fix everything as users might use the new sdk + new FSharp.Core to target net5.0 (unless we make Giraffe 6.0 net6.0 only, which is a bit drastic) but it'll help the majority of the users.

Anybody using Ply's uply/uvtask CEs would then have to add their own reference to ply or (my preference) drop those for task/vtask coming from FSharp.Core.

**Comment by dustinmoris** [comment]
I guess this one is done by #496?
