### ISSUE TITLE
When will Giraffe 6.0.0 final be released?

### ISSUE THREAD

**Issue by cmeeren** [giraffe-fsharp/Giraffe#500]
Is Giraffe 6.0.0 final "just around the corner", or still weeks or more off?

Asking because I will soon upgrade all my APIs to .NET 6, but due to the maintenance overhead, I'd like to also upgrade to Giraffe 6 at the same time, unless it's still a ways off.

**Comment by forki** [comment]
It needs to wait for the compiler fix to https://github.com/dotnet/fsharp/issues/12359 to land in .NET SDK.

**Comment by cmeeren** [comment]
Thanks for the clarification!

**Comment by tforkmann** [comment]
Hi, Saturn is still relying on a Giraffe prerelease version. Any plans to release a stable Giraffe 6 version?

Cheers,

Tim
