### ISSUE TITLE
Json.ISerializer Interface does not exist

### ISSUE THREAD

**Issue by colinbobolin** [giraffe-fsharp/Giraffe#501]
In the documentation [regarding json](https://github.com/giraffe-fsharp/Giraffe/blob/master/DOCUMENTATION.md#json), there is a suggestion to add `Json.ISerializer` to the services. I do not know where this interface is coming from, but I cannot find it. I'm trying to use the Utf8JsonSerializer but cannot figure out how to configure it.

**Comment by kurt-mueller-osumc** [comment]
Could it be referring to this?

https://docs.microsoft.com/en-us/dotnet/api/microsoft.graph.iserializer?view=graph-core-dotnet

**Comment by TheAngryByrd** [comment]
https://github.com/giraffe-fsharp/Giraffe/blob/43836267a8b249177078ccad737d5f2932d3c2d0/src/Giraffe/Json.fs#L13 ?

**Comment by colinbobolin** [comment]
ah, it seems I might need to update my version of Giraffe. Thanks for the pointers.
