### ISSUE TITLE
What's needed for a final .NET 6 release?

### ISSUE THREAD

**Issue by cartermp** [giraffe-fsharp/Giraffe#509]
See here: https://github.com/giraffe-fsharp/Giraffe/issues/500#issuecomment-1073779793

The F# compiler has the necessary fixes out to make this a reality. Saturn has released with .NET 6 support, but still depends on the prerelease of Giraffe.

Is there anything else needed to bump to non-preview @dustinmoris @slang25?

**Comment by tforkmann** [comment]
Any news on that?
Thanks,

Tim

**Comment by dustinmoris** [comment]
Sorry for the delay. Done now!

**Comment by tforkmann** [comment]
Thanks, Dustin!

**Comment by forki** [comment]
Hugs!

Dustin Moris Gorski ***@***.***> schrieb am Sa., 9. Apr.
2022, 11:38:
