### ISSUE TITLE
Deprecated construct after migration to ASP.NET Core 6

### ISSUE THREAD

**Issue by OkayX6** [giraffe-fsharp/Giraffe#524]
Hi,

Just so we remember, I am getting this warning with this piece of code since ASP.NET Core 6 :)

![image](https://user-images.githubusercontent.com/1169339/189871778-1a818b0e-8475-413f-8e6f-fa6049b13042.png)

Thanks!

**Comment by 64J0** [comment]
I believe this issue can be closed now after merging [this PR](https://github.com/giraffe-fsharp/Giraffe/pull/547).

**Comment by 64J0** [comment]
It's weird that the GitHub automation to close the issue automatically is not working properly. I never noticed this behavior before.
