### ISSUE TITLE
dotnet new giraffe installs older SDK in fsproj file

### ISSUE THREAD

**Issue by mengelhart** [giraffe-fsharp/Giraffe#525]
Hello 

I'm new to using Giraffe and when I install the giraffe template and then run `dotnet new giraffe` the fsproj file seems pretty out of date.  .NET 6 has been out almost a year and .NET 7 is coming out this month.  Also the giraffe version is seemingly pretty far off.

```
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
    <AssemblyName>advidly.App</AssemblyName>
    <EnableDefaultContentItems>false</EnableDefaultContentItems>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Giraffe" Version="5.0.0-rc-6" />
    <PackageReference Include="Giraffe.ViewEngine" Version="1.3.*" />
    <PackageReference Include="Ply" Version="0.3.*" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="Program.fs" />
  </ItemGroup>

  <ItemGroup>
    <None Include="web.config" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="WebRoot\**\*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
</Project>
```

I'd be happy to look at attempting to get a PR for updating this if someone could point in the right direction as I'm new to the F# community.

Thanks

**Comment by Banashek** [comment]
There are a couple of PRs to the template repo for this, though no merged solution yet: https://github.com/giraffe-fsharp/giraffe-template/pulls

https://github.com/giraffe-fsharp/giraffe-template/pull/43
https://github.com/giraffe-fsharp/giraffe-template/pull/44

**Comment by 64J0** [comment]
Up

**Comment by TheAngryByrd** [comment]
https://github.com/giraffe-fsharp/giraffe-template/issues/48 needs to be completed before this can be closed.

**Comment by dustinmoris** [comment]
For now I've fixed the AppVeyor CI pipeline. A new template should have been published to NuGet now. Version 1.4 has .NET 7 in the template thanks to the contribution!

**Comment by 64J0** [comment]
Great news, thanks for the fix!
