### ISSUE TITLE
Update to .NET7

### ISSUE THREAD

**Issue by tforkmann** [giraffe-fsharp/Giraffe#526]
Its this time of the year...

@dustinmoris Do you mind releasing a new Giraffe version?
I would the try to upgrade Saturn.

Thanks,

Tim

**Comment by tforkmann** [comment]
Any news on that? Cheers, Tim

**Comment by slang25** [comment]
I thought there was no need to update the tfm if there was no binary breaking changes in dependencies and we weren't taking advantage of new APIs?

**Comment by TheAngryByrd** [comment]
Done in https://github.com/giraffe-fsharp/Giraffe/pull/527
