### ISSUE TITLE
Supporting rate limiting middleware

### ISSUE THREAD

**Issue by hotyes** [giraffe-fsharp/Giraffe#528]
Hi there, just wondering how to support middleware in a giraffe application ? thanks

https://learn.microsoft.com/en-us/aspnet/core/performance/rate-limit?view=aspnetcore-7.0

**Comment by dustinmoris** [comment]
So Giraffe is enabled via middleware itself, you can plug other middleware just before or after if you want.

**Comment by 64J0** [comment]
Thanks for the detailed answer @TheAngryByrd. Just to clarify my use case, I would like to add a final middleware that would collect some information related to the request and expose to my metrics system.

Only in this last step, we have access to the response status code, for example.

I could add some custom code to the endpoint handlers, but I prefer to leverage the middleware approach whenever possible (it reminds me of the [pipes and filters](https://learn.microsoft.com/en-us/azure/architecture/patterns/pipes-and-filters) architecture). It helps to keep the code clean, in my opinion.

**Comment by dustinmoris** [comment]
I'm closing this as I believe the question has been answered :)
