### ISSUE TITLE
WriteStreamAsync and WriteFileStreamAsync documented examples are wrong

### ISSUE THREAD

**Issue by davidtimovski** [giraffe-fsharp/Giraffe#530]
This is used as an example for `WriteStreamAsync` in the documentation page:

    let someHandler : HttpHandler =
        fun (next : HttpFunc) (ctx : HttpContext) ->
            task {
                // Do stuff
                return! ctx.WriteStreamAsync
                    true // enableRangeProcessing
                    someStream
                    None // eTag
                    None // lastModified
            }

But it doesn't compile. The correct usage is this:

    let someHandler : HttpHandler =
        fun (next : HttpFunc) (ctx : HttpContext) ->
            task {
                // Do stuff
                return! ctx.WriteStreamAsync (true, someStream, None, None)
            }

Same for `WriteFileStreamAsync`.

**Comment by 64J0** [comment]
Indeed, this is also happening in my VS Code (notice the warning):

![image](https://github.com/giraffe-fsharp/Giraffe/assets/50725287/1c7f2927-4c15-48f2-96a5-2f61f99198f3)

Steps that I used to reproduce:

```bash
dotnet new -i "giraffe-template::1.3.0"

dotnet new giraffe -o giraffe-test

# open Program.fs on IDE
# add "open Microsoft.AspNetCore.Http" so it does not raise warns regarding HttpContext
# paste the code example after function "configureCors"
```

Error logs:

```bash
/giraffe-test/Program.fs(95,17): error FS0001: This expression was expected to have type    'bool * 'a * Net.Http.Headers.EntityTagHeaderValue option * DateTimeOffset option'    but here has type    'bool' [/giraffe-test/giraffe-test.fsproj]
/giraffe-test/Program.fs(94,21): error FS0003: This value is not a function and cannot be applied. [/giraffe-test/giraffe-test.fsproj]
```

**Comment by 64J0** [comment]
When using the tuple syntax:

![image](https://github.com/giraffe-fsharp/Giraffe/assets/50725287/bc82dadb-cd48-4915-93f1-eedb8571e1d3)

**Comment by TheAngryByrd** [comment]
Closed via https://github.com/giraffe-fsharp/Giraffe/pull/545
