### ISSUE TITLE
XML Docs don't appear to be working

### ISSUE THREAD

**Issue by isaacabraham** [giraffe-fsharp/Giraffe#532]
Maybe this is a Rider thing? I'm just trying a codebase and getting no documentation for any Giraffe symbols e.g. for the `route` function this is what I see in Rider:

![image](https://user-images.githubusercontent.com/1781813/209819326-7e3672b3-b5f1-40bd-97ce-8c70f1513f11.png)

However if I go to definition I indeed do see there's proper XML Docs on the value:

![image](https://user-images.githubusercontent.com/1781813/209819390-b65c9b12-a418-4e6f-a4f4-93239e3501fb.png)

I've tested out local functions and regular `///` and full XML Doc stuff seems to be working just fine. I would expect to see the following in Rider (I just copied the implementation above into my project including the docs).

![image](https://user-images.githubusercontent.com/1781813/209819585-dc781625-bb43-44fc-aba5-e0734f7a8663.png)

**Comment by dustinmoris** [comment]
How do you view the documentation? When I hover with my mouse over a Giraffe function in Rider then I get the docs shown like this:

<img width="858" alt="image" src="https://user-images.githubusercontent.com/4580714/209932077-8eb80129-a968-49e6-987c-7a43b216bb6e.png">

**Comment by 64J0** [comment]
Any updates here?

**Comment by Trigun27** [comment]
rider, the latest version
XML commets are ok 

![image](https://github.com/giraffe-fsharp/Giraffe/assets/5838703/31069a98-c643-4a11-8ebe-b9316383ccfa)

**Comment by dustinmoris** [comment]
Thanks for confirming @Trigun27

**Comment by isaacabraham** [comment]
Sorry - I've just tested and can confirm that it's all working now. I had feared it was that the docs weren't being bundled in the NuGet package but it appears that it was a Rider thing.
