### ISSUE TITLE
Is Giraffe.EndpointRouting considered best practice?

### ISSUE THREAD

**Issue by SIRHAMY** [giraffe-fsharp/Giraffe#534]
Giraffe currently supports a few router types like:

* Default router - what most of the docs talk about
* Endpoint Routing - a subset of routing functionality that integrates with ASP.NET Core Routing (see: [Endpoint Routing](https://github.com/giraffe-fsharp/Giraffe/blob/master/DOCUMENTATION.md#endpoint-routing))
* Token Router - Another alt (see: [Token Router](https://github.com/giraffe-fsharp/Giraffe/blob/master/DOCUMENTATION.md#tokenrouter))

There may be more but these are the ones I see prevalent in docs / online.

* Q1: Do we have a preferred routing choice? A "recommended" path?
* Q2: If so, can we make that a bit more clear in the docs by making that choice more prevalent?

I am particularly curious about the direction the framework is going in terms of routing as I have little context on this.

# Why do I care / why am I asking?

Problem: Confusion among new-comers for getting setup "right"

"Right" / "Best Practice" is always debatable but typically I see providing a sane default / recommendation as helpful for adoption.

# Routing Best Practice

Based on my current knowledge / research it seems that Endpoint Routing is the future of Giraffe. [Saturn seems to agree](https://saturnframework.org/explanations/endpoint-routing.html)

Based on tradeoffs I think this seems reasonable:

Pros

* Benefits from updates to ASP.NET Core
* Has access to underlying [ASP.NET Core routing](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/routing?view=aspnetcore-5.0) -> though many may not need / use this
* Performant - ~8% faster than "default" router if we trust [Web Frameworks Benchmark](https://web-frameworks-benchmark.netlify.app/result?l=fsharp)

Cons

* Not all Giraffe routing functions are supported -> but a critical mass to do most everything you need
* Requires a flat list of endpoints -> but may make some things simpler (though some previous patterns are broken based on open Issues like [Authentication](https://github.com/giraffe-fsharp/Giraffe/issues/480))
* All endpoints are case insensitive -> [debatable](https://stackoverflow.com/questions/7996919/should-url-be-case-sensitive) whether this matters

# Next Steps

Curious if people have thoughts on this / think this matters. 

In particular, some perspectives I think of that could be valuable:

* Giraffe maintainers
* Saturn maintainers
* Experienced Giraffe users
* New Giraffe users

**Comment by 64J0** [comment]
Good question! I would like to know as well.

**Comment by dustinmoris** [comment]
Yes, the Endpoint Routing approach is the recommended way. All routing in ASP.NET Core was migrated to comply with the Endpoint Routing API I believe so it makes only sense for Giraffe to also follow this path as it will naturally have a higher ability to interop with other middlewares and libraries wihch use the Endpoint Routing APIs.

**Comment by 64J0** [comment]
I added to the documentation the information that `Giraffe.EndpointRouting` is considered best practice with [this PR](https://github.com/giraffe-fsharp/Giraffe/pull/556). I assume this is sufficient to close this issue. 

Please, open a follow-up issue or start a discussion if you need more clarification or would like to get deeper into this topic.
