### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by enzonun** [giraffe-fsharp/Giraffe#538]
is this project under active development ?

**Comment by dustinmoris** [comment]
Hey, admittedly it's not been under active development for a while and I'm sorry for that. I can see how that is disruptive and I'm open for suggestions and I will consider all options presented to keep this project alive if that is the interest of the community

**Comment by retendo** [comment]
That would be great! Even if the project would only receive the occasional bug fix, it would at least keep it usable for existing projects in production. I don't have time to maintain it either, but I would be happy to review a PR every now and then. Maybe there's motivation of the Saturn maintainers to chip in as well? (cc @Krzysztof-Cieslak @NinoFloris @baronfel @64J0)

**Comment by dustinmoris** [comment]
@TheAngryByrd I have sent you an invite to become an Admin and made the admin group capable of pushing to main and releases themselves. I have also started to talk to someone about the longevity prospect of this project and finding some time to work on it. I'll post an update if there is more to say. However if anyone has an interest to help here out and devote some time then please let me know and I can invite you to this repo!

**Comment by TheAngryByrd** [comment]
@dustinmoris Thanks! I went ahead and merged a few things. I figured out the release process (documenting it when I'm finished). Looks like we need a new nuget key. 
```
Run dotnet nuget push ./nupkg/*.nupkg --source $NUGET_FEED --skip-duplicate --api-key $NUGET_KEY
Pushing Giraffe.6.1.0-beta001.nupkg to 'https://www.nuget.org/api/v2/package'...
  PUT https://www.nuget.org/api/v2/package/
  Forbidden https://www.nuget.org/api/v2/package/ 591ms
error: Response status code does not indicate success: 403 (The specified API key is invalid, has expired, or does not have permission to access the specified package.).

```

Can you add me to that set of repos/nuget organization as well? Otherwise we'll have to pester you for new nuget keys every year.

**Comment by dustinmoris** [comment]
I've updated the NuGet key for now to not block anything and will look into how to add mroe people to the Nuget repo a little later today.

**Comment by Trigun27** [comment]
Hi, It's a really nice project! 
I would like to help somehow too. My main experince is C#. I wrote several pet projects in F#

**Comment by Trigun27** [comment]
I could update Giraffe's templates. Upgrade them to .net7 version and update build scripts

**Comment by Trigun27** [comment]
ping) 

Be the way, is there any communication channel to discuss PR and hole project? 
Slack channel seems more dead, than alive

**Comment by 64J0** [comment]
Maybe [GitHub discussions](https://github.com/giraffe-fsharp/Giraffe/discussions), but it seems dead as well.

**Comment by dustinmoris** [comment]
@Trigun27 Help would be much appreciated. If you really want to get involved then perhaps you could start by helping out with some PRs and we can take it from there and see how much you want to get involved in the future?

**Comment by Trigun27** [comment]
> @Trigun27 Help would be much appreciated. If you really want to get involved then perhaps you could start by helping out with some PRs and we can take it from there and see how much you want to get involved in the future?

Should I take already open PRs or something from the issue?

**Comment by josh-degraw** [comment]
Update:

https://github.com/fsprojects/.github/issues/49

**Comment by 64J0** [comment]
> is this project under active development ?

It is. I'm working on it during my free time along with other maintainers.

**Comment by 64J0** [comment]
I'll close this issue now. Please keep opening new issues, starting new discussions and sending your PRs so we can review your ideas. It could take some time, but eventually we'll take care of it.
