### ISSUE TITLE
NullReferenceException in requiresAuthentication funciton

### ISSUE THREAD

**Issue by clement128** [giraffe-fsharp/Giraffe#552]
If the user is not null and user.Identity is null, the function will throw this exception.

In my case is because of the JWT token is not valid

```
Unexpected error
System.NullReferenceException: Object reference not set to an instance of an object.
   at Giraffe.Auth.requiresAuthentication@76.Invoke(ClaimsPrincipal user)
```

**Comment by 64J0** [comment]
Fixed by https://github.com/giraffe-fsharp/Giraffe/pull/557.
