### ISSUE TITLE
Never decalre reader with `use` on `ctx.Request.Body`

### ISSUE THREAD

**Issue by xperiandri** [giraffe-fsharp/Giraffe#564]
this
https://github.com/giraffe-fsharp/Giraffe/blob/6a364955f77609e9265c577ddd817c92fefe104c/src/Giraffe/HttpContextExtensions.fs#L197
disposes body, because the reader disposes underlying stream.
Which must not be done in any case!

**Comment by 64J0** [comment]
I did not get it, what is the problem with disposing the request body after reading it?

**Comment by xperiandri** [comment]
The problem is that Giraffe is not an owner of it. The owner of it is an appropriate ASP.NET core middleware.
Giraffe must not dispose the stuff it is not owner of.
It leads to unexpected behavior for the consumer.

**Comment by 64J0** [comment]
I see, thanks for the explanation. I agree then!

**Comment by Banashek** [comment]
Looks like the `leaveOpen` parameter could be specified to allow disposal of the `StreamReader` without disposing the underlying resource: [doc reference](https://learn.microsoft.com/en-us/dotnet/api/system.io.streamreader.-ctor?view=net-8.0#system-io-streamreader-ctor(system-io-stream-system-text-encoding-system-boolean-system-int32-system-boolean))

```fs
use reader = new StreamReader(ctx.Request.Body, Encoding.UTF8, leaveOpen = true)
```
