### ISSUE TITLE
Upgrade to .NET 8

### ISSUE THREAD

**Issue by 64J0** [giraffe-fsharp/Giraffe#565]
## Description

Upgrade to .NET 8 to use its improvements.

- https://devblogs.microsoft.com/dotnet/announcing-fsharp-8/

**Comment by Banashek** [comment]
The TestHost version 8.0 doesn't support 6 or 7 (which are the current targets for the lib and tests):
https://www.nuget.org/packages/Microsoft.AspNetCore.TestHost#supportedframeworks-body-tab

**Comment by kerams** [comment]
This is a library - you'll benefit from .NET 8 (runtime) improvements by changing the TFM of your *application*.

**Comment by 64J0** [comment]
@kerams I understand part of your point. But take the ASP.NET middlewares that were added in .NET 7 and 8 for example. We could eventually create our own Giraffe-based version of it. Maybe there are other features added that we could use to improve the current codebase, which I'm not considering right now.

Other than that, I assume it is more interesting for potential contributors to use the latest language (F#) and tools (.NET/ASP.NET) when interacting with this codebase.

**Comment by baronfel** [comment]
ok, so this is more about updating the _tools_ here to .NET 8 - so updating build scripts, CI/CD, etc. The library itself is a secondary goal?

**Comment by 64J0** [comment]
> ok, so this is more about updating the tools here to .NET 8 - so updating build scripts, CI/CD, etc. The library itself is a secondary goal?

Exactly @baronfel. Do you think this makes sense?

**Comment by baronfel** [comment]
absolutely!

**Comment by 64J0** [comment]
Closing with this PR https://github.com/giraffe-fsharp/Giraffe/pull/574.
