### ISSUE TITLE
Giraffe 6.2 is breaks against Microsoft.IO.RecyclableMemoryStream 3.0.0

### ISSUE THREAD

**Issue by da9l** [giraffe-fsharp/Giraffe#570]
When upgrading a project dependent of Giraffe 6.2 to .Net 8, one risks getting an exception in runtime due to unintended upgrade of Microsoft.IO.RecyclableMemoryStream to version 3.0.0

A System.MissingMethodException is thrown with the message:
`Method not found: 'System.IO.MemoryStream Microsoft.IO.RecyclableMemoryStreamManager.GetStream(System.String)'.`

Workaround:
Pin Microsoft.IO.RecyclableMemoryStream to  2.3.2

Suggested fix: Upgrade Giraffe to .Net 8 and the v3.0.0 of Microsoft.IO.RecyclableMemoryStream

**Comment by fpellet** [comment]
@dustinmoris @TheAngryByrd I proposed the PR #566 . How can I help you review and merge?

**Comment by da9l** [comment]
@fpellet and others, there is a Giraffe maintenance issue that likely need to be resolved first before any PR:s can be reviewed and merged. See Dustin's tweet: https://twitter.com/dustinmoris/status/1749417442214883420 and the discussion ongoing in Oxpecker https://github.com/Lanayx/Oxpecker/discussions/4

**Comment by clement128** [comment]
Hello, Same issue here, any update on this? thanks

**Comment by 64J0** [comment]
Hi, I'll be looking into this problem during this week.

**Comment by 64J0** [comment]
Hi @da9l and @clement128, I have merged @fpellet's PR right now, and it's generating the pre-release version `6.4.0-alpha-1`. Can you please validate on your code if this new version is working correctly?

**Comment by clement128** [comment]
hi, thanks @64J0 looking good on my side

**Comment by 64J0** [comment]
Thanks for the fast reply. I'll close this issue as completed now! Great job @fpellet 👏🏼 👏🏼 👏🏼

**Comment by 64J0** [comment]
Sure, I'll do that later today

**Comment by 64J0** [comment]
Done.
