### ISSUE TITLE
Start using fantomas to validate code submissions with CI

### ISSUE THREAD

**Issue by 64J0** [giraffe-fsharp/Giraffe#581]
## Description:

In order to keep the code properly formatted we could leverage [fantomas](https://github.com/fsprojects/fantomas), by running this tool on CI.

**Comment by reinux** [comment]
Is there a way to have it respect blank lines? I tend not to use Fantomas because it didn't respect paragraph breaks last time I checked.

**Comment by 64J0** [comment]
I did not get your point @reinux. You mention in comments, right? 

In my experience it does not touch comments, but just to make sure, can you please provide an example for what you have in mind?

Other than that, considering that this has the potential to influence all the codebase, I think it's worth adding it only to the samples along with the tests first.

**Comment by reinux** [comment]
Stuff like this:

```fsharp
let arrange itemWidth (getSize: 'i -> int * int) (canvasWidth, canvasHeight) (items: 'i list) : Rect list =
  let rec loop (left, top) bottom items rects =
    match items with
    | x :: xs ->
      let width, height = getSize x
      let ratio = (float width / float height)
      let width, height = itemWidth, int (float height / ratio)
                          // inserted empty line
      if top + height > canvasHeight then
        rects

      elif left + width > canvasWidth then
        if bottom + height > canvasHeight then
          rects
        else
          let rect =
            { left = 0
              top = bottom
              width = width
              height = height }
                          // inserted empty line
          loop (0, bottom) (bottom + height) xs (rect :: rects)

      else
        let rect =
          { left = left
            top = top
            width = width
            height = height }
                          // inserted empty line
        loop (left + rect.left, top) (max bottom (top + rect.height)) xs (rect :: rects)
    | [] -> rects

  loop (0, 0) 0 items [] |> List.rev
```

I have my code arranged into paragraphs that indicate conceptually related code, but Fantomas places blank lines between let bindings and return expressions, which makes the deliberate paragraph groupings harder to spot.

Sorry, I didn't mean for this to be a Fantomas question on the Giraffe repo, but I was just thinking that it would be nice to have if Giraffe gets the Fantomas treatment.

**Comment by 64J0** [comment]
Got it now, thanks for the clarification. I'm not sure if it's possible but I'll take a look.

**Comment by 64J0** [comment]
We can configure Fantomas using some `.editorconfig` commands: https://fsprojects.github.io/fantomas/docs/end-users/Configuration.html.
