### ISSUE TITLE
[README] Suggestion for "Getting Started"'s "Doing it manually"

### ISSUE THREAD

**Issue by toraritte** [giraffe-fsharp/Giraffe#584]
Being new to .NET (and ASP.NET Core, especially), a little bit "handholding" would have speeded up getting started with Giraffe. For example, after playing with Suave, I was baffled that there are no instructions on how to run a Giraffe project, but then I realized that the whole point is that Giraffe builds on top of ASP.NET Core, so I have to their docs... Feel stupid when I think about this, but a not would complete newcomers.

Would you be open for a PR along these lines? 

> > NOTE How to run a Giraffe project?
> > Remember that a Giraffe project plugs into the ASP.NET Core pipeline or is itself an ASP.NET Core application, so if you have questions not covered here or in the Giraffe documentation, then it is probably a topic for the [ASP.NET Core documentation](https://learn.microsoft.com/en-us/aspnet/core/). In this case, see the [Get started with ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/getting-started/) article.
>  
> ### Doing it manually
> 
> Steps from 0. to 5. follow [Get started with F# with command-line tools - .NET | Microsoft Learn](https://learn.microsoft.com/en-us/dotnet/fsharp/get-started/get-started-command-line).
> 
> 0. (_OPTIONAL_) Create a new solution.
> 1. Enter the solution's directory.
> 2. Create an empty ASP.NET Core project.
> 3. (_OPTIONAL_) Add new project to solution.
> 4. Enter the project's directory.
> 5. Install dependencies.
> 6. Add the your or the suggested entry points.
> 7. Run project.
> 
> ```
> STEP_0 dotnet new sln -o GiraffeExample
> STEP_1 cd GiraffeExample
> STEP_2 dotnet new web -lang "F#" -o src/GiraffeWeb
> STEP_3 dotnet sln add src/GiraffeWeb/GiraffeWeb.fsproj 
> STEP_4 cd src/GiraffeWeb/
> 
> STEP_5 dotnet add package Microsoft.AspNetCore.App
> STEP_5 dotnet add package Giraffe
> 
> STEP_6 (add your entry point)
> 
> STEP_7 dotnet watch run
> ```

**Comment by 64J0** [comment]
Hi @toraritte, thanks for reaching out, we already have something related [here](https://github.com/giraffe-fsharp/Giraffe/tree/master?tab=readme-ov-file#getting-started). It does not mention the command to run the project, so this could be enhanced for sure.

For the sln creation, it's not really necessary, so I would not add it there.

Other than that, we have some documentation that you may think it's useful (although lacking information, or more detailed explanations) [here](https://github.com/giraffe-fsharp/Giraffe/blob/master/DOCUMENTATION.md). Maybe you can help to update it there, what do you think?

**Comment by toraritte** [comment]
> Other than that, we have some documentation that you may think it's useful (although lacking information, or more detailed explanations) [here](https://github.com/giraffe-fsharp/Giraffe/blob/master/DOCUMENTATION.md). Maybe you can help to update it there, what do you think?

Sounds good! I'm still working my way through the [docs](https://github.com/giraffe-fsharp/Giraffe/blob/master/DOCUMENTATION.md), so I'll be on the lookout. Will close this in the meantime. Thanks!
