### ISSUE TITLE
Remove NuGet API key from the repository

### ISSUE THREAD

**Issue by Unknown6656** [giraffe-fsharp/Giraffe#586]
Hey mate, I noticed that your NuGet API key is publicly visible: https://github.com/giraffe-fsharp/Giraffe/blob/30aecaf97971a86c42d1fb7a7132b124664602cc/appveyor.yml#L18

It would be wise to remove the file from the GitHub repository or the .git tracking, as anyone with that API key could potentially push malicious packages to NuGet under your name.....

**Comment by slang25** [comment]
Thanks for raising this with us. The `secure` part of the appveyor file is a feature where we can use an encrypted secret, and it is decrypted appropriate by appveyor only for this repo.

**Comment by dustinmoris** [comment]
Correct, the key is not public there. It is a cipher of the plaintext key and only AppVeyor holds an account specific private key to decrypt this value.

**Comment by Unknown6656** [comment]
Ah thank you very much for the clarification! :)

I was already afraid that this was the plain-text NuGet API token.
