### ISSUE TITLE
Add documentation and sample for OpenApi configuration

### ISSUE THREAD

**Issue by 64J0** [giraffe-fsharp/Giraffe#602]
## Description:

Follow-up from this PR: https://github.com/giraffe-fsharp/Giraffe/pull/599.

We basically need:

- Some paragraphs explaining how this configuration works and how to use it;
- A new sample project.

**Comment by nojaf** [comment]
@64J0 are you also on board with moving https://github.com/mrtz-j/Giraffe.OpenApi to https://github.com/giraffe-fsharp?

**Comment by 64J0** [comment]
> @64J0 are you also on board with moving https://github.com/mrtz-j/Giraffe.OpenApi to https://github.com/giraffe-fsharp?

@nojaf +/-, I know the intention exists, but I'm not aware of how the move process is going.

**Comment by nojaf** [comment]
Well @mrtz-j would need to transfer it (via https://github.com/mrtz-j/Giraffe.OpenApi/transfer) to `giraffe-fsharp`.

Once that happens I believe some administrator in that organization would need to accept and that would move it. A next step would then be to setup NuGet publishing similar to how it work for the other packages in Giraffe.

**Comment by mrtz-j** [comment]
I am ready to transfer it. I just need to know if I need to be invited into the organization or if I can simply transfer it and then create PRs to finish the Nuget-setup/README.

**Comment by nojaf** [comment]
Did you try

![image](https://github.com/user-attachments/assets/edddf779-8784-4bac-a823-cbf448d48696)

**Comment by mrtz-j** [comment]
Yes. I tried to do that, but I got the following error message: `You don’t have the permission to create public repositories on giraffe-fsharp`.

**Comment by nojaf** [comment]
Ok, I see. Could you add me as administrator to the repo? I believe I'm admin in the giraffe-org

**Comment by nojaf** [comment]
@mrtz-j thanks for the invite, I need to be admin on that repo as well to transfer it.

**Comment by mrtz-j** [comment]
It seems that I can only give you `write`/`read` access, but not `admin`. I'll try to transfer the repo to you instead, and then you can add it to the Giraffe org.

**Comment by 64J0** [comment]
Imported the repo here: https://github.com/giraffe-fsharp/Giraffe.OpenApi.

**Comment by mrtz-j** [comment]
I've added some documentation and update the sample app [here](https://github.com/giraffe-fsharp/Giraffe.OpenApi/pull/5). It will use the available ENV-variables to push it to NuGet.
