### ISSUE TITLE
F# compatible json serializer

### ISSUE THREAD

**Issue by fpellet** [giraffe-fsharp/Giraffe#604]
With the change https://github.com/giraffe-fsharp/Giraffe/issues/560 , unlike before, by default the serializer is not compatible with the particularities of F#.
As this can have an impact on performance, I can understand not setting a compatible serializer by default, even if I think it's a shame for a project like Giraffe.
Nevertheless, I suggest making things easier and offering a configuration via `FSharp.SystemTextJson` for example directly via the project so as not to add a barrier.

**Comment by 64J0** [comment]
Thanks for opening this PR @fpellet.

> Nevertheless, I suggest making things easier and offering a configuration via [FSharp.SystemTextJson](https://github.com/Tarmil/FSharp.SystemTextJson) for example directly via the project so as not to add a barrier.

Fair enough, I like this idea!

**Comment by forki** [comment]
adding to this the current docs are broken:

![image](https://github.com/user-attachments/assets/95ec48a4-3429-4ce7-91e3-52c3bc72f105)

that thing can't be found.

**Comment by fpellet** [comment]
For FSharp.SystemTextJson , I'll have a look this weekend.

@forki  indeed, I had seen that and forgot to put it back up.

Necessary changes in the doc: 
It need to delete this constructor, and initialize in services:
```
services.AddSingleton<Json.ISerializer>(fun serviceProvider ->
            NewtonsoftJson.Serializer(JsonSerializerSettings(), serviceProvider.GetService<Microsoft.IO.RecyclableMemoryStreamManager>()) :> Json.ISerializer) |> ignore
```

**Comment by 64J0** [comment]
I think it makes sense to add a new sample to this project showing how to add NewtonsoftJson back properly.

**Comment by fpellet** [comment]
@64J0 It's possible to publish new version? 😊

**Comment by nojaf** [comment]
As in new NuGet or publish documentation?
(For NuGet 7.0.0 is published right? https://www.nuget.org/packages/Giraffe/7.0.0)

**Comment by fpellet** [comment]
Nuget to use new serialiser without copy paste

**Comment by 64J0** [comment]
> @64J0 It's possible to publish new version? 😊

Sure, working on it right now.

**Comment by 64J0** [comment]
Version 7.0.1 released 🚀 https://www.nuget.org/packages/Giraffe/7.0.1
